/*
Aura Frame API - Unofficial

Reverse Engineered API for Aura Frames

API version: 0.0.1
Contact: dave@mudsite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package auraframes

import (
	"encoding/json"
)

// Frame struct for Frame
type Frame struct {
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	UserId *string `json:"user_id,omitempty"`
	SoftwareVersion *string `json:"software_version,omitempty"`
	BuildVersion *string `json:"build_version,omitempty"`
	HwAndroidVersion *string `json:"hw_android_version,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	HandledAt *string `json:"handled_at,omitempty"`
	DeletedAt *string `json:"deleted_at,omitempty"`
	UpdatedAtOnClient *string `json:"updated_at_on_client,omitempty"`
	LastImpressionAt *string `json:"last_impression_at,omitempty"`
	Orientation *string `json:"orientation,omitempty"`
	AutoBrightness *bool `json:"auto_brightness,omitempty"`
	MinBrightness *string `json:"min_brightness,omitempty"`
	MaxBrightness *string `json:"max_brightness,omitempty"`
	Brightness *string `json:"brightness,omitempty"`
	SenseMotion *bool `json:"sense_motion,omitempty"`
	DefaultSpeed *string `json:"default_speed,omitempty"`
	SlideshowInterval *string `json:"slideshow_interval,omitempty"`
	SlideshowAuto *bool `json:"slideshow_auto,omitempty"`
	Digits *string `json:"digits,omitempty"`
	ContributorTokens []ContributorTokens `json:"contributor_tokens,omitempty"`
	HwSerial *string `json:"hw_serial,omitempty"`
	MattingColor *string `json:"matting_color,omitempty"`
	TrimColor *string `json:"trim_color,omitempty"`
	IsHandling *bool `json:"is_handling,omitempty"`
	CalibrationsLastModifiedAt *string `json:"calibrations_last_modified_at,omitempty"`
	GesturesOn *bool `json:"gestures_on,omitempty"`
	PortraitPairingOff *string `json:"portrait_pairing_off,omitempty"`
	LivePhotosOn *bool `json:"live_photos_on,omitempty"`
	AutoProcessedPlaylistIds []string `json:"auto_processed_playlist_ids,omitempty"`
	TimeZone *string `json:"time_zone,omitempty"`
	WifiNetwork *string `json:"wifi_network,omitempty"`
	ColdBootAt *string `json:"cold_boot_at,omitempty"`
	IsCharityWaterFrame *bool `json:"is_charity_water_frame,omitempty"`
	NumAssets *string `json:"num_assets,omitempty"`
	ThanksOn *bool `json:"thanks_on,omitempty"`
	FrameQueueUrl *string `json:"frame_queue_url,omitempty"`
	ClientQueueUrl *string `json:"client_queue_url,omitempty"`
	ScheduledDisplaySleep *bool `json:"scheduled_display_sleep,omitempty"`
	ScheduledDisplayOnAt *string `json:"scheduled_display_on_at,omitempty"`
	ScheduledDisplayOffAt *string `json:"scheduled_display_off_at,omitempty"`
	ForcedWifiState *string `json:"forced_wifi_state,omitempty"`
	ForcedWifiRecipientEmail *string `json:"forced_wifi_recipient_email,omitempty"`
	IsAnalogFrame *bool `json:"is_analog_frame,omitempty"`
	ControlType *string `json:"control_type,omitempty"`
	DisplayAspectRatio *string `json:"display_aspect_ratio,omitempty"`
	HasClaimableGift *bool `json:"has_claimable_gift,omitempty"`
	GiftBillingHint *string `json:"gift_billing_hint,omitempty"`
	Locale *string `json:"locale,omitempty"`
	FrameType *string `json:"frame_type,omitempty"`
	Description *string `json:"description,omitempty"`
	RepresentativeAssetId *string `json:"representative_asset_id,omitempty"`
	SortMode *string `json:"sort_mode,omitempty"`
	EmailAddress *string `json:"email_address,omitempty"`
	Features []string `json:"features,omitempty"`
	Volume *string `json:"volume,omitempty"`
	User *User `json:"user,omitempty"`
	Playlists []string `json:"playlists,omitempty"`
	LastFeedItem *FeedItem `json:"last_feed_item,omitempty"`
	LastImpression *Impression `json:"last_impression,omitempty"`
	RecentAssets []Asset `json:"recent_assets,omitempty"`
	Contributors []User `json:"contributors,omitempty"`
	FrameEnvironment *FrameEnvironment `json:"frame_environment,omitempty"`
	CurrentPrintSet *string `json:"current_print_set,omitempty"`
	FirstPrintSet *string `json:"first_print_set,omitempty"`
	ChildAlbums []string `json:"child_albums,omitempty"`
	SmartAdds []string `json:"smart_adds,omitempty"`
}

// NewFrame instantiates a new Frame object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFrame() *Frame {
	this := Frame{}
	return &this
}

// NewFrameWithDefaults instantiates a new Frame object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFrameWithDefaults() *Frame {
	this := Frame{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Frame) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Frame) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Frame) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Frame) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Frame) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Frame) SetName(v string) {
	o.Name = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *Frame) GetUserId() string {
	if o == nil || o.UserId == nil {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetUserIdOk() (*string, bool) {
	if o == nil || o.UserId == nil {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *Frame) HasUserId() bool {
	if o != nil && o.UserId != nil {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *Frame) SetUserId(v string) {
	o.UserId = &v
}

// GetSoftwareVersion returns the SoftwareVersion field value if set, zero value otherwise.
func (o *Frame) GetSoftwareVersion() string {
	if o == nil || o.SoftwareVersion == nil {
		var ret string
		return ret
	}
	return *o.SoftwareVersion
}

// GetSoftwareVersionOk returns a tuple with the SoftwareVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetSoftwareVersionOk() (*string, bool) {
	if o == nil || o.SoftwareVersion == nil {
		return nil, false
	}
	return o.SoftwareVersion, true
}

// HasSoftwareVersion returns a boolean if a field has been set.
func (o *Frame) HasSoftwareVersion() bool {
	if o != nil && o.SoftwareVersion != nil {
		return true
	}

	return false
}

// SetSoftwareVersion gets a reference to the given string and assigns it to the SoftwareVersion field.
func (o *Frame) SetSoftwareVersion(v string) {
	o.SoftwareVersion = &v
}

// GetBuildVersion returns the BuildVersion field value if set, zero value otherwise.
func (o *Frame) GetBuildVersion() string {
	if o == nil || o.BuildVersion == nil {
		var ret string
		return ret
	}
	return *o.BuildVersion
}

// GetBuildVersionOk returns a tuple with the BuildVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetBuildVersionOk() (*string, bool) {
	if o == nil || o.BuildVersion == nil {
		return nil, false
	}
	return o.BuildVersion, true
}

// HasBuildVersion returns a boolean if a field has been set.
func (o *Frame) HasBuildVersion() bool {
	if o != nil && o.BuildVersion != nil {
		return true
	}

	return false
}

// SetBuildVersion gets a reference to the given string and assigns it to the BuildVersion field.
func (o *Frame) SetBuildVersion(v string) {
	o.BuildVersion = &v
}

// GetHwAndroidVersion returns the HwAndroidVersion field value if set, zero value otherwise.
func (o *Frame) GetHwAndroidVersion() string {
	if o == nil || o.HwAndroidVersion == nil {
		var ret string
		return ret
	}
	return *o.HwAndroidVersion
}

// GetHwAndroidVersionOk returns a tuple with the HwAndroidVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetHwAndroidVersionOk() (*string, bool) {
	if o == nil || o.HwAndroidVersion == nil {
		return nil, false
	}
	return o.HwAndroidVersion, true
}

// HasHwAndroidVersion returns a boolean if a field has been set.
func (o *Frame) HasHwAndroidVersion() bool {
	if o != nil && o.HwAndroidVersion != nil {
		return true
	}

	return false
}

// SetHwAndroidVersion gets a reference to the given string and assigns it to the HwAndroidVersion field.
func (o *Frame) SetHwAndroidVersion(v string) {
	o.HwAndroidVersion = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Frame) GetCreatedAt() string {
	if o == nil || o.CreatedAt == nil {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetCreatedAtOk() (*string, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Frame) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *Frame) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Frame) GetUpdatedAt() string {
	if o == nil || o.UpdatedAt == nil {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetUpdatedAtOk() (*string, bool) {
	if o == nil || o.UpdatedAt == nil {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Frame) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt != nil {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *Frame) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetHandledAt returns the HandledAt field value if set, zero value otherwise.
func (o *Frame) GetHandledAt() string {
	if o == nil || o.HandledAt == nil {
		var ret string
		return ret
	}
	return *o.HandledAt
}

// GetHandledAtOk returns a tuple with the HandledAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetHandledAtOk() (*string, bool) {
	if o == nil || o.HandledAt == nil {
		return nil, false
	}
	return o.HandledAt, true
}

// HasHandledAt returns a boolean if a field has been set.
func (o *Frame) HasHandledAt() bool {
	if o != nil && o.HandledAt != nil {
		return true
	}

	return false
}

// SetHandledAt gets a reference to the given string and assigns it to the HandledAt field.
func (o *Frame) SetHandledAt(v string) {
	o.HandledAt = &v
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise.
func (o *Frame) GetDeletedAt() string {
	if o == nil || o.DeletedAt == nil {
		var ret string
		return ret
	}
	return *o.DeletedAt
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetDeletedAtOk() (*string, bool) {
	if o == nil || o.DeletedAt == nil {
		return nil, false
	}
	return o.DeletedAt, true
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *Frame) HasDeletedAt() bool {
	if o != nil && o.DeletedAt != nil {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given string and assigns it to the DeletedAt field.
func (o *Frame) SetDeletedAt(v string) {
	o.DeletedAt = &v
}

// GetUpdatedAtOnClient returns the UpdatedAtOnClient field value if set, zero value otherwise.
func (o *Frame) GetUpdatedAtOnClient() string {
	if o == nil || o.UpdatedAtOnClient == nil {
		var ret string
		return ret
	}
	return *o.UpdatedAtOnClient
}

// GetUpdatedAtOnClientOk returns a tuple with the UpdatedAtOnClient field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetUpdatedAtOnClientOk() (*string, bool) {
	if o == nil || o.UpdatedAtOnClient == nil {
		return nil, false
	}
	return o.UpdatedAtOnClient, true
}

// HasUpdatedAtOnClient returns a boolean if a field has been set.
func (o *Frame) HasUpdatedAtOnClient() bool {
	if o != nil && o.UpdatedAtOnClient != nil {
		return true
	}

	return false
}

// SetUpdatedAtOnClient gets a reference to the given string and assigns it to the UpdatedAtOnClient field.
func (o *Frame) SetUpdatedAtOnClient(v string) {
	o.UpdatedAtOnClient = &v
}

// GetLastImpressionAt returns the LastImpressionAt field value if set, zero value otherwise.
func (o *Frame) GetLastImpressionAt() string {
	if o == nil || o.LastImpressionAt == nil {
		var ret string
		return ret
	}
	return *o.LastImpressionAt
}

// GetLastImpressionAtOk returns a tuple with the LastImpressionAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetLastImpressionAtOk() (*string, bool) {
	if o == nil || o.LastImpressionAt == nil {
		return nil, false
	}
	return o.LastImpressionAt, true
}

// HasLastImpressionAt returns a boolean if a field has been set.
func (o *Frame) HasLastImpressionAt() bool {
	if o != nil && o.LastImpressionAt != nil {
		return true
	}

	return false
}

// SetLastImpressionAt gets a reference to the given string and assigns it to the LastImpressionAt field.
func (o *Frame) SetLastImpressionAt(v string) {
	o.LastImpressionAt = &v
}

// GetOrientation returns the Orientation field value if set, zero value otherwise.
func (o *Frame) GetOrientation() string {
	if o == nil || o.Orientation == nil {
		var ret string
		return ret
	}
	return *o.Orientation
}

// GetOrientationOk returns a tuple with the Orientation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetOrientationOk() (*string, bool) {
	if o == nil || o.Orientation == nil {
		return nil, false
	}
	return o.Orientation, true
}

// HasOrientation returns a boolean if a field has been set.
func (o *Frame) HasOrientation() bool {
	if o != nil && o.Orientation != nil {
		return true
	}

	return false
}

// SetOrientation gets a reference to the given string and assigns it to the Orientation field.
func (o *Frame) SetOrientation(v string) {
	o.Orientation = &v
}

// GetAutoBrightness returns the AutoBrightness field value if set, zero value otherwise.
func (o *Frame) GetAutoBrightness() bool {
	if o == nil || o.AutoBrightness == nil {
		var ret bool
		return ret
	}
	return *o.AutoBrightness
}

// GetAutoBrightnessOk returns a tuple with the AutoBrightness field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetAutoBrightnessOk() (*bool, bool) {
	if o == nil || o.AutoBrightness == nil {
		return nil, false
	}
	return o.AutoBrightness, true
}

// HasAutoBrightness returns a boolean if a field has been set.
func (o *Frame) HasAutoBrightness() bool {
	if o != nil && o.AutoBrightness != nil {
		return true
	}

	return false
}

// SetAutoBrightness gets a reference to the given bool and assigns it to the AutoBrightness field.
func (o *Frame) SetAutoBrightness(v bool) {
	o.AutoBrightness = &v
}

// GetMinBrightness returns the MinBrightness field value if set, zero value otherwise.
func (o *Frame) GetMinBrightness() string {
	if o == nil || o.MinBrightness == nil {
		var ret string
		return ret
	}
	return *o.MinBrightness
}

// GetMinBrightnessOk returns a tuple with the MinBrightness field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetMinBrightnessOk() (*string, bool) {
	if o == nil || o.MinBrightness == nil {
		return nil, false
	}
	return o.MinBrightness, true
}

// HasMinBrightness returns a boolean if a field has been set.
func (o *Frame) HasMinBrightness() bool {
	if o != nil && o.MinBrightness != nil {
		return true
	}

	return false
}

// SetMinBrightness gets a reference to the given string and assigns it to the MinBrightness field.
func (o *Frame) SetMinBrightness(v string) {
	o.MinBrightness = &v
}

// GetMaxBrightness returns the MaxBrightness field value if set, zero value otherwise.
func (o *Frame) GetMaxBrightness() string {
	if o == nil || o.MaxBrightness == nil {
		var ret string
		return ret
	}
	return *o.MaxBrightness
}

// GetMaxBrightnessOk returns a tuple with the MaxBrightness field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetMaxBrightnessOk() (*string, bool) {
	if o == nil || o.MaxBrightness == nil {
		return nil, false
	}
	return o.MaxBrightness, true
}

// HasMaxBrightness returns a boolean if a field has been set.
func (o *Frame) HasMaxBrightness() bool {
	if o != nil && o.MaxBrightness != nil {
		return true
	}

	return false
}

// SetMaxBrightness gets a reference to the given string and assigns it to the MaxBrightness field.
func (o *Frame) SetMaxBrightness(v string) {
	o.MaxBrightness = &v
}

// GetBrightness returns the Brightness field value if set, zero value otherwise.
func (o *Frame) GetBrightness() string {
	if o == nil || o.Brightness == nil {
		var ret string
		return ret
	}
	return *o.Brightness
}

// GetBrightnessOk returns a tuple with the Brightness field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetBrightnessOk() (*string, bool) {
	if o == nil || o.Brightness == nil {
		return nil, false
	}
	return o.Brightness, true
}

// HasBrightness returns a boolean if a field has been set.
func (o *Frame) HasBrightness() bool {
	if o != nil && o.Brightness != nil {
		return true
	}

	return false
}

// SetBrightness gets a reference to the given string and assigns it to the Brightness field.
func (o *Frame) SetBrightness(v string) {
	o.Brightness = &v
}

// GetSenseMotion returns the SenseMotion field value if set, zero value otherwise.
func (o *Frame) GetSenseMotion() bool {
	if o == nil || o.SenseMotion == nil {
		var ret bool
		return ret
	}
	return *o.SenseMotion
}

// GetSenseMotionOk returns a tuple with the SenseMotion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetSenseMotionOk() (*bool, bool) {
	if o == nil || o.SenseMotion == nil {
		return nil, false
	}
	return o.SenseMotion, true
}

// HasSenseMotion returns a boolean if a field has been set.
func (o *Frame) HasSenseMotion() bool {
	if o != nil && o.SenseMotion != nil {
		return true
	}

	return false
}

// SetSenseMotion gets a reference to the given bool and assigns it to the SenseMotion field.
func (o *Frame) SetSenseMotion(v bool) {
	o.SenseMotion = &v
}

// GetDefaultSpeed returns the DefaultSpeed field value if set, zero value otherwise.
func (o *Frame) GetDefaultSpeed() string {
	if o == nil || o.DefaultSpeed == nil {
		var ret string
		return ret
	}
	return *o.DefaultSpeed
}

// GetDefaultSpeedOk returns a tuple with the DefaultSpeed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetDefaultSpeedOk() (*string, bool) {
	if o == nil || o.DefaultSpeed == nil {
		return nil, false
	}
	return o.DefaultSpeed, true
}

// HasDefaultSpeed returns a boolean if a field has been set.
func (o *Frame) HasDefaultSpeed() bool {
	if o != nil && o.DefaultSpeed != nil {
		return true
	}

	return false
}

// SetDefaultSpeed gets a reference to the given string and assigns it to the DefaultSpeed field.
func (o *Frame) SetDefaultSpeed(v string) {
	o.DefaultSpeed = &v
}

// GetSlideshowInterval returns the SlideshowInterval field value if set, zero value otherwise.
func (o *Frame) GetSlideshowInterval() string {
	if o == nil || o.SlideshowInterval == nil {
		var ret string
		return ret
	}
	return *o.SlideshowInterval
}

// GetSlideshowIntervalOk returns a tuple with the SlideshowInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetSlideshowIntervalOk() (*string, bool) {
	if o == nil || o.SlideshowInterval == nil {
		return nil, false
	}
	return o.SlideshowInterval, true
}

// HasSlideshowInterval returns a boolean if a field has been set.
func (o *Frame) HasSlideshowInterval() bool {
	if o != nil && o.SlideshowInterval != nil {
		return true
	}

	return false
}

// SetSlideshowInterval gets a reference to the given string and assigns it to the SlideshowInterval field.
func (o *Frame) SetSlideshowInterval(v string) {
	o.SlideshowInterval = &v
}

// GetSlideshowAuto returns the SlideshowAuto field value if set, zero value otherwise.
func (o *Frame) GetSlideshowAuto() bool {
	if o == nil || o.SlideshowAuto == nil {
		var ret bool
		return ret
	}
	return *o.SlideshowAuto
}

// GetSlideshowAutoOk returns a tuple with the SlideshowAuto field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetSlideshowAutoOk() (*bool, bool) {
	if o == nil || o.SlideshowAuto == nil {
		return nil, false
	}
	return o.SlideshowAuto, true
}

// HasSlideshowAuto returns a boolean if a field has been set.
func (o *Frame) HasSlideshowAuto() bool {
	if o != nil && o.SlideshowAuto != nil {
		return true
	}

	return false
}

// SetSlideshowAuto gets a reference to the given bool and assigns it to the SlideshowAuto field.
func (o *Frame) SetSlideshowAuto(v bool) {
	o.SlideshowAuto = &v
}

// GetDigits returns the Digits field value if set, zero value otherwise.
func (o *Frame) GetDigits() string {
	if o == nil || o.Digits == nil {
		var ret string
		return ret
	}
	return *o.Digits
}

// GetDigitsOk returns a tuple with the Digits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetDigitsOk() (*string, bool) {
	if o == nil || o.Digits == nil {
		return nil, false
	}
	return o.Digits, true
}

// HasDigits returns a boolean if a field has been set.
func (o *Frame) HasDigits() bool {
	if o != nil && o.Digits != nil {
		return true
	}

	return false
}

// SetDigits gets a reference to the given string and assigns it to the Digits field.
func (o *Frame) SetDigits(v string) {
	o.Digits = &v
}

// GetContributorTokens returns the ContributorTokens field value if set, zero value otherwise.
func (o *Frame) GetContributorTokens() []ContributorTokens {
	if o == nil || o.ContributorTokens == nil {
		var ret []ContributorTokens
		return ret
	}
	return o.ContributorTokens
}

// GetContributorTokensOk returns a tuple with the ContributorTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetContributorTokensOk() ([]ContributorTokens, bool) {
	if o == nil || o.ContributorTokens == nil {
		return nil, false
	}
	return o.ContributorTokens, true
}

// HasContributorTokens returns a boolean if a field has been set.
func (o *Frame) HasContributorTokens() bool {
	if o != nil && o.ContributorTokens != nil {
		return true
	}

	return false
}

// SetContributorTokens gets a reference to the given []ContributorTokens and assigns it to the ContributorTokens field.
func (o *Frame) SetContributorTokens(v []ContributorTokens) {
	o.ContributorTokens = v
}

// GetHwSerial returns the HwSerial field value if set, zero value otherwise.
func (o *Frame) GetHwSerial() string {
	if o == nil || o.HwSerial == nil {
		var ret string
		return ret
	}
	return *o.HwSerial
}

// GetHwSerialOk returns a tuple with the HwSerial field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetHwSerialOk() (*string, bool) {
	if o == nil || o.HwSerial == nil {
		return nil, false
	}
	return o.HwSerial, true
}

// HasHwSerial returns a boolean if a field has been set.
func (o *Frame) HasHwSerial() bool {
	if o != nil && o.HwSerial != nil {
		return true
	}

	return false
}

// SetHwSerial gets a reference to the given string and assigns it to the HwSerial field.
func (o *Frame) SetHwSerial(v string) {
	o.HwSerial = &v
}

// GetMattingColor returns the MattingColor field value if set, zero value otherwise.
func (o *Frame) GetMattingColor() string {
	if o == nil || o.MattingColor == nil {
		var ret string
		return ret
	}
	return *o.MattingColor
}

// GetMattingColorOk returns a tuple with the MattingColor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetMattingColorOk() (*string, bool) {
	if o == nil || o.MattingColor == nil {
		return nil, false
	}
	return o.MattingColor, true
}

// HasMattingColor returns a boolean if a field has been set.
func (o *Frame) HasMattingColor() bool {
	if o != nil && o.MattingColor != nil {
		return true
	}

	return false
}

// SetMattingColor gets a reference to the given string and assigns it to the MattingColor field.
func (o *Frame) SetMattingColor(v string) {
	o.MattingColor = &v
}

// GetTrimColor returns the TrimColor field value if set, zero value otherwise.
func (o *Frame) GetTrimColor() string {
	if o == nil || o.TrimColor == nil {
		var ret string
		return ret
	}
	return *o.TrimColor
}

// GetTrimColorOk returns a tuple with the TrimColor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetTrimColorOk() (*string, bool) {
	if o == nil || o.TrimColor == nil {
		return nil, false
	}
	return o.TrimColor, true
}

// HasTrimColor returns a boolean if a field has been set.
func (o *Frame) HasTrimColor() bool {
	if o != nil && o.TrimColor != nil {
		return true
	}

	return false
}

// SetTrimColor gets a reference to the given string and assigns it to the TrimColor field.
func (o *Frame) SetTrimColor(v string) {
	o.TrimColor = &v
}

// GetIsHandling returns the IsHandling field value if set, zero value otherwise.
func (o *Frame) GetIsHandling() bool {
	if o == nil || o.IsHandling == nil {
		var ret bool
		return ret
	}
	return *o.IsHandling
}

// GetIsHandlingOk returns a tuple with the IsHandling field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetIsHandlingOk() (*bool, bool) {
	if o == nil || o.IsHandling == nil {
		return nil, false
	}
	return o.IsHandling, true
}

// HasIsHandling returns a boolean if a field has been set.
func (o *Frame) HasIsHandling() bool {
	if o != nil && o.IsHandling != nil {
		return true
	}

	return false
}

// SetIsHandling gets a reference to the given bool and assigns it to the IsHandling field.
func (o *Frame) SetIsHandling(v bool) {
	o.IsHandling = &v
}

// GetCalibrationsLastModifiedAt returns the CalibrationsLastModifiedAt field value if set, zero value otherwise.
func (o *Frame) GetCalibrationsLastModifiedAt() string {
	if o == nil || o.CalibrationsLastModifiedAt == nil {
		var ret string
		return ret
	}
	return *o.CalibrationsLastModifiedAt
}

// GetCalibrationsLastModifiedAtOk returns a tuple with the CalibrationsLastModifiedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetCalibrationsLastModifiedAtOk() (*string, bool) {
	if o == nil || o.CalibrationsLastModifiedAt == nil {
		return nil, false
	}
	return o.CalibrationsLastModifiedAt, true
}

// HasCalibrationsLastModifiedAt returns a boolean if a field has been set.
func (o *Frame) HasCalibrationsLastModifiedAt() bool {
	if o != nil && o.CalibrationsLastModifiedAt != nil {
		return true
	}

	return false
}

// SetCalibrationsLastModifiedAt gets a reference to the given string and assigns it to the CalibrationsLastModifiedAt field.
func (o *Frame) SetCalibrationsLastModifiedAt(v string) {
	o.CalibrationsLastModifiedAt = &v
}

// GetGesturesOn returns the GesturesOn field value if set, zero value otherwise.
func (o *Frame) GetGesturesOn() bool {
	if o == nil || o.GesturesOn == nil {
		var ret bool
		return ret
	}
	return *o.GesturesOn
}

// GetGesturesOnOk returns a tuple with the GesturesOn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetGesturesOnOk() (*bool, bool) {
	if o == nil || o.GesturesOn == nil {
		return nil, false
	}
	return o.GesturesOn, true
}

// HasGesturesOn returns a boolean if a field has been set.
func (o *Frame) HasGesturesOn() bool {
	if o != nil && o.GesturesOn != nil {
		return true
	}

	return false
}

// SetGesturesOn gets a reference to the given bool and assigns it to the GesturesOn field.
func (o *Frame) SetGesturesOn(v bool) {
	o.GesturesOn = &v
}

// GetPortraitPairingOff returns the PortraitPairingOff field value if set, zero value otherwise.
func (o *Frame) GetPortraitPairingOff() string {
	if o == nil || o.PortraitPairingOff == nil {
		var ret string
		return ret
	}
	return *o.PortraitPairingOff
}

// GetPortraitPairingOffOk returns a tuple with the PortraitPairingOff field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetPortraitPairingOffOk() (*string, bool) {
	if o == nil || o.PortraitPairingOff == nil {
		return nil, false
	}
	return o.PortraitPairingOff, true
}

// HasPortraitPairingOff returns a boolean if a field has been set.
func (o *Frame) HasPortraitPairingOff() bool {
	if o != nil && o.PortraitPairingOff != nil {
		return true
	}

	return false
}

// SetPortraitPairingOff gets a reference to the given string and assigns it to the PortraitPairingOff field.
func (o *Frame) SetPortraitPairingOff(v string) {
	o.PortraitPairingOff = &v
}

// GetLivePhotosOn returns the LivePhotosOn field value if set, zero value otherwise.
func (o *Frame) GetLivePhotosOn() bool {
	if o == nil || o.LivePhotosOn == nil {
		var ret bool
		return ret
	}
	return *o.LivePhotosOn
}

// GetLivePhotosOnOk returns a tuple with the LivePhotosOn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetLivePhotosOnOk() (*bool, bool) {
	if o == nil || o.LivePhotosOn == nil {
		return nil, false
	}
	return o.LivePhotosOn, true
}

// HasLivePhotosOn returns a boolean if a field has been set.
func (o *Frame) HasLivePhotosOn() bool {
	if o != nil && o.LivePhotosOn != nil {
		return true
	}

	return false
}

// SetLivePhotosOn gets a reference to the given bool and assigns it to the LivePhotosOn field.
func (o *Frame) SetLivePhotosOn(v bool) {
	o.LivePhotosOn = &v
}

// GetAutoProcessedPlaylistIds returns the AutoProcessedPlaylistIds field value if set, zero value otherwise.
func (o *Frame) GetAutoProcessedPlaylistIds() []string {
	if o == nil || o.AutoProcessedPlaylistIds == nil {
		var ret []string
		return ret
	}
	return o.AutoProcessedPlaylistIds
}

// GetAutoProcessedPlaylistIdsOk returns a tuple with the AutoProcessedPlaylistIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetAutoProcessedPlaylistIdsOk() ([]string, bool) {
	if o == nil || o.AutoProcessedPlaylistIds == nil {
		return nil, false
	}
	return o.AutoProcessedPlaylistIds, true
}

// HasAutoProcessedPlaylistIds returns a boolean if a field has been set.
func (o *Frame) HasAutoProcessedPlaylistIds() bool {
	if o != nil && o.AutoProcessedPlaylistIds != nil {
		return true
	}

	return false
}

// SetAutoProcessedPlaylistIds gets a reference to the given []string and assigns it to the AutoProcessedPlaylistIds field.
func (o *Frame) SetAutoProcessedPlaylistIds(v []string) {
	o.AutoProcessedPlaylistIds = v
}

// GetTimeZone returns the TimeZone field value if set, zero value otherwise.
func (o *Frame) GetTimeZone() string {
	if o == nil || o.TimeZone == nil {
		var ret string
		return ret
	}
	return *o.TimeZone
}

// GetTimeZoneOk returns a tuple with the TimeZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetTimeZoneOk() (*string, bool) {
	if o == nil || o.TimeZone == nil {
		return nil, false
	}
	return o.TimeZone, true
}

// HasTimeZone returns a boolean if a field has been set.
func (o *Frame) HasTimeZone() bool {
	if o != nil && o.TimeZone != nil {
		return true
	}

	return false
}

// SetTimeZone gets a reference to the given string and assigns it to the TimeZone field.
func (o *Frame) SetTimeZone(v string) {
	o.TimeZone = &v
}

// GetWifiNetwork returns the WifiNetwork field value if set, zero value otherwise.
func (o *Frame) GetWifiNetwork() string {
	if o == nil || o.WifiNetwork == nil {
		var ret string
		return ret
	}
	return *o.WifiNetwork
}

// GetWifiNetworkOk returns a tuple with the WifiNetwork field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetWifiNetworkOk() (*string, bool) {
	if o == nil || o.WifiNetwork == nil {
		return nil, false
	}
	return o.WifiNetwork, true
}

// HasWifiNetwork returns a boolean if a field has been set.
func (o *Frame) HasWifiNetwork() bool {
	if o != nil && o.WifiNetwork != nil {
		return true
	}

	return false
}

// SetWifiNetwork gets a reference to the given string and assigns it to the WifiNetwork field.
func (o *Frame) SetWifiNetwork(v string) {
	o.WifiNetwork = &v
}

// GetColdBootAt returns the ColdBootAt field value if set, zero value otherwise.
func (o *Frame) GetColdBootAt() string {
	if o == nil || o.ColdBootAt == nil {
		var ret string
		return ret
	}
	return *o.ColdBootAt
}

// GetColdBootAtOk returns a tuple with the ColdBootAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetColdBootAtOk() (*string, bool) {
	if o == nil || o.ColdBootAt == nil {
		return nil, false
	}
	return o.ColdBootAt, true
}

// HasColdBootAt returns a boolean if a field has been set.
func (o *Frame) HasColdBootAt() bool {
	if o != nil && o.ColdBootAt != nil {
		return true
	}

	return false
}

// SetColdBootAt gets a reference to the given string and assigns it to the ColdBootAt field.
func (o *Frame) SetColdBootAt(v string) {
	o.ColdBootAt = &v
}

// GetIsCharityWaterFrame returns the IsCharityWaterFrame field value if set, zero value otherwise.
func (o *Frame) GetIsCharityWaterFrame() bool {
	if o == nil || o.IsCharityWaterFrame == nil {
		var ret bool
		return ret
	}
	return *o.IsCharityWaterFrame
}

// GetIsCharityWaterFrameOk returns a tuple with the IsCharityWaterFrame field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetIsCharityWaterFrameOk() (*bool, bool) {
	if o == nil || o.IsCharityWaterFrame == nil {
		return nil, false
	}
	return o.IsCharityWaterFrame, true
}

// HasIsCharityWaterFrame returns a boolean if a field has been set.
func (o *Frame) HasIsCharityWaterFrame() bool {
	if o != nil && o.IsCharityWaterFrame != nil {
		return true
	}

	return false
}

// SetIsCharityWaterFrame gets a reference to the given bool and assigns it to the IsCharityWaterFrame field.
func (o *Frame) SetIsCharityWaterFrame(v bool) {
	o.IsCharityWaterFrame = &v
}

// GetNumAssets returns the NumAssets field value if set, zero value otherwise.
func (o *Frame) GetNumAssets() string {
	if o == nil || o.NumAssets == nil {
		var ret string
		return ret
	}
	return *o.NumAssets
}

// GetNumAssetsOk returns a tuple with the NumAssets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetNumAssetsOk() (*string, bool) {
	if o == nil || o.NumAssets == nil {
		return nil, false
	}
	return o.NumAssets, true
}

// HasNumAssets returns a boolean if a field has been set.
func (o *Frame) HasNumAssets() bool {
	if o != nil && o.NumAssets != nil {
		return true
	}

	return false
}

// SetNumAssets gets a reference to the given string and assigns it to the NumAssets field.
func (o *Frame) SetNumAssets(v string) {
	o.NumAssets = &v
}

// GetThanksOn returns the ThanksOn field value if set, zero value otherwise.
func (o *Frame) GetThanksOn() bool {
	if o == nil || o.ThanksOn == nil {
		var ret bool
		return ret
	}
	return *o.ThanksOn
}

// GetThanksOnOk returns a tuple with the ThanksOn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetThanksOnOk() (*bool, bool) {
	if o == nil || o.ThanksOn == nil {
		return nil, false
	}
	return o.ThanksOn, true
}

// HasThanksOn returns a boolean if a field has been set.
func (o *Frame) HasThanksOn() bool {
	if o != nil && o.ThanksOn != nil {
		return true
	}

	return false
}

// SetThanksOn gets a reference to the given bool and assigns it to the ThanksOn field.
func (o *Frame) SetThanksOn(v bool) {
	o.ThanksOn = &v
}

// GetFrameQueueUrl returns the FrameQueueUrl field value if set, zero value otherwise.
func (o *Frame) GetFrameQueueUrl() string {
	if o == nil || o.FrameQueueUrl == nil {
		var ret string
		return ret
	}
	return *o.FrameQueueUrl
}

// GetFrameQueueUrlOk returns a tuple with the FrameQueueUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetFrameQueueUrlOk() (*string, bool) {
	if o == nil || o.FrameQueueUrl == nil {
		return nil, false
	}
	return o.FrameQueueUrl, true
}

// HasFrameQueueUrl returns a boolean if a field has been set.
func (o *Frame) HasFrameQueueUrl() bool {
	if o != nil && o.FrameQueueUrl != nil {
		return true
	}

	return false
}

// SetFrameQueueUrl gets a reference to the given string and assigns it to the FrameQueueUrl field.
func (o *Frame) SetFrameQueueUrl(v string) {
	o.FrameQueueUrl = &v
}

// GetClientQueueUrl returns the ClientQueueUrl field value if set, zero value otherwise.
func (o *Frame) GetClientQueueUrl() string {
	if o == nil || o.ClientQueueUrl == nil {
		var ret string
		return ret
	}
	return *o.ClientQueueUrl
}

// GetClientQueueUrlOk returns a tuple with the ClientQueueUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetClientQueueUrlOk() (*string, bool) {
	if o == nil || o.ClientQueueUrl == nil {
		return nil, false
	}
	return o.ClientQueueUrl, true
}

// HasClientQueueUrl returns a boolean if a field has been set.
func (o *Frame) HasClientQueueUrl() bool {
	if o != nil && o.ClientQueueUrl != nil {
		return true
	}

	return false
}

// SetClientQueueUrl gets a reference to the given string and assigns it to the ClientQueueUrl field.
func (o *Frame) SetClientQueueUrl(v string) {
	o.ClientQueueUrl = &v
}

// GetScheduledDisplaySleep returns the ScheduledDisplaySleep field value if set, zero value otherwise.
func (o *Frame) GetScheduledDisplaySleep() bool {
	if o == nil || o.ScheduledDisplaySleep == nil {
		var ret bool
		return ret
	}
	return *o.ScheduledDisplaySleep
}

// GetScheduledDisplaySleepOk returns a tuple with the ScheduledDisplaySleep field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetScheduledDisplaySleepOk() (*bool, bool) {
	if o == nil || o.ScheduledDisplaySleep == nil {
		return nil, false
	}
	return o.ScheduledDisplaySleep, true
}

// HasScheduledDisplaySleep returns a boolean if a field has been set.
func (o *Frame) HasScheduledDisplaySleep() bool {
	if o != nil && o.ScheduledDisplaySleep != nil {
		return true
	}

	return false
}

// SetScheduledDisplaySleep gets a reference to the given bool and assigns it to the ScheduledDisplaySleep field.
func (o *Frame) SetScheduledDisplaySleep(v bool) {
	o.ScheduledDisplaySleep = &v
}

// GetScheduledDisplayOnAt returns the ScheduledDisplayOnAt field value if set, zero value otherwise.
func (o *Frame) GetScheduledDisplayOnAt() string {
	if o == nil || o.ScheduledDisplayOnAt == nil {
		var ret string
		return ret
	}
	return *o.ScheduledDisplayOnAt
}

// GetScheduledDisplayOnAtOk returns a tuple with the ScheduledDisplayOnAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetScheduledDisplayOnAtOk() (*string, bool) {
	if o == nil || o.ScheduledDisplayOnAt == nil {
		return nil, false
	}
	return o.ScheduledDisplayOnAt, true
}

// HasScheduledDisplayOnAt returns a boolean if a field has been set.
func (o *Frame) HasScheduledDisplayOnAt() bool {
	if o != nil && o.ScheduledDisplayOnAt != nil {
		return true
	}

	return false
}

// SetScheduledDisplayOnAt gets a reference to the given string and assigns it to the ScheduledDisplayOnAt field.
func (o *Frame) SetScheduledDisplayOnAt(v string) {
	o.ScheduledDisplayOnAt = &v
}

// GetScheduledDisplayOffAt returns the ScheduledDisplayOffAt field value if set, zero value otherwise.
func (o *Frame) GetScheduledDisplayOffAt() string {
	if o == nil || o.ScheduledDisplayOffAt == nil {
		var ret string
		return ret
	}
	return *o.ScheduledDisplayOffAt
}

// GetScheduledDisplayOffAtOk returns a tuple with the ScheduledDisplayOffAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetScheduledDisplayOffAtOk() (*string, bool) {
	if o == nil || o.ScheduledDisplayOffAt == nil {
		return nil, false
	}
	return o.ScheduledDisplayOffAt, true
}

// HasScheduledDisplayOffAt returns a boolean if a field has been set.
func (o *Frame) HasScheduledDisplayOffAt() bool {
	if o != nil && o.ScheduledDisplayOffAt != nil {
		return true
	}

	return false
}

// SetScheduledDisplayOffAt gets a reference to the given string and assigns it to the ScheduledDisplayOffAt field.
func (o *Frame) SetScheduledDisplayOffAt(v string) {
	o.ScheduledDisplayOffAt = &v
}

// GetForcedWifiState returns the ForcedWifiState field value if set, zero value otherwise.
func (o *Frame) GetForcedWifiState() string {
	if o == nil || o.ForcedWifiState == nil {
		var ret string
		return ret
	}
	return *o.ForcedWifiState
}

// GetForcedWifiStateOk returns a tuple with the ForcedWifiState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetForcedWifiStateOk() (*string, bool) {
	if o == nil || o.ForcedWifiState == nil {
		return nil, false
	}
	return o.ForcedWifiState, true
}

// HasForcedWifiState returns a boolean if a field has been set.
func (o *Frame) HasForcedWifiState() bool {
	if o != nil && o.ForcedWifiState != nil {
		return true
	}

	return false
}

// SetForcedWifiState gets a reference to the given string and assigns it to the ForcedWifiState field.
func (o *Frame) SetForcedWifiState(v string) {
	o.ForcedWifiState = &v
}

// GetForcedWifiRecipientEmail returns the ForcedWifiRecipientEmail field value if set, zero value otherwise.
func (o *Frame) GetForcedWifiRecipientEmail() string {
	if o == nil || o.ForcedWifiRecipientEmail == nil {
		var ret string
		return ret
	}
	return *o.ForcedWifiRecipientEmail
}

// GetForcedWifiRecipientEmailOk returns a tuple with the ForcedWifiRecipientEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetForcedWifiRecipientEmailOk() (*string, bool) {
	if o == nil || o.ForcedWifiRecipientEmail == nil {
		return nil, false
	}
	return o.ForcedWifiRecipientEmail, true
}

// HasForcedWifiRecipientEmail returns a boolean if a field has been set.
func (o *Frame) HasForcedWifiRecipientEmail() bool {
	if o != nil && o.ForcedWifiRecipientEmail != nil {
		return true
	}

	return false
}

// SetForcedWifiRecipientEmail gets a reference to the given string and assigns it to the ForcedWifiRecipientEmail field.
func (o *Frame) SetForcedWifiRecipientEmail(v string) {
	o.ForcedWifiRecipientEmail = &v
}

// GetIsAnalogFrame returns the IsAnalogFrame field value if set, zero value otherwise.
func (o *Frame) GetIsAnalogFrame() bool {
	if o == nil || o.IsAnalogFrame == nil {
		var ret bool
		return ret
	}
	return *o.IsAnalogFrame
}

// GetIsAnalogFrameOk returns a tuple with the IsAnalogFrame field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetIsAnalogFrameOk() (*bool, bool) {
	if o == nil || o.IsAnalogFrame == nil {
		return nil, false
	}
	return o.IsAnalogFrame, true
}

// HasIsAnalogFrame returns a boolean if a field has been set.
func (o *Frame) HasIsAnalogFrame() bool {
	if o != nil && o.IsAnalogFrame != nil {
		return true
	}

	return false
}

// SetIsAnalogFrame gets a reference to the given bool and assigns it to the IsAnalogFrame field.
func (o *Frame) SetIsAnalogFrame(v bool) {
	o.IsAnalogFrame = &v
}

// GetControlType returns the ControlType field value if set, zero value otherwise.
func (o *Frame) GetControlType() string {
	if o == nil || o.ControlType == nil {
		var ret string
		return ret
	}
	return *o.ControlType
}

// GetControlTypeOk returns a tuple with the ControlType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetControlTypeOk() (*string, bool) {
	if o == nil || o.ControlType == nil {
		return nil, false
	}
	return o.ControlType, true
}

// HasControlType returns a boolean if a field has been set.
func (o *Frame) HasControlType() bool {
	if o != nil && o.ControlType != nil {
		return true
	}

	return false
}

// SetControlType gets a reference to the given string and assigns it to the ControlType field.
func (o *Frame) SetControlType(v string) {
	o.ControlType = &v
}

// GetDisplayAspectRatio returns the DisplayAspectRatio field value if set, zero value otherwise.
func (o *Frame) GetDisplayAspectRatio() string {
	if o == nil || o.DisplayAspectRatio == nil {
		var ret string
		return ret
	}
	return *o.DisplayAspectRatio
}

// GetDisplayAspectRatioOk returns a tuple with the DisplayAspectRatio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetDisplayAspectRatioOk() (*string, bool) {
	if o == nil || o.DisplayAspectRatio == nil {
		return nil, false
	}
	return o.DisplayAspectRatio, true
}

// HasDisplayAspectRatio returns a boolean if a field has been set.
func (o *Frame) HasDisplayAspectRatio() bool {
	if o != nil && o.DisplayAspectRatio != nil {
		return true
	}

	return false
}

// SetDisplayAspectRatio gets a reference to the given string and assigns it to the DisplayAspectRatio field.
func (o *Frame) SetDisplayAspectRatio(v string) {
	o.DisplayAspectRatio = &v
}

// GetHasClaimableGift returns the HasClaimableGift field value if set, zero value otherwise.
func (o *Frame) GetHasClaimableGift() bool {
	if o == nil || o.HasClaimableGift == nil {
		var ret bool
		return ret
	}
	return *o.HasClaimableGift
}

// GetHasClaimableGiftOk returns a tuple with the HasClaimableGift field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetHasClaimableGiftOk() (*bool, bool) {
	if o == nil || o.HasClaimableGift == nil {
		return nil, false
	}
	return o.HasClaimableGift, true
}

// HasHasClaimableGift returns a boolean if a field has been set.
func (o *Frame) HasHasClaimableGift() bool {
	if o != nil && o.HasClaimableGift != nil {
		return true
	}

	return false
}

// SetHasClaimableGift gets a reference to the given bool and assigns it to the HasClaimableGift field.
func (o *Frame) SetHasClaimableGift(v bool) {
	o.HasClaimableGift = &v
}

// GetGiftBillingHint returns the GiftBillingHint field value if set, zero value otherwise.
func (o *Frame) GetGiftBillingHint() string {
	if o == nil || o.GiftBillingHint == nil {
		var ret string
		return ret
	}
	return *o.GiftBillingHint
}

// GetGiftBillingHintOk returns a tuple with the GiftBillingHint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetGiftBillingHintOk() (*string, bool) {
	if o == nil || o.GiftBillingHint == nil {
		return nil, false
	}
	return o.GiftBillingHint, true
}

// HasGiftBillingHint returns a boolean if a field has been set.
func (o *Frame) HasGiftBillingHint() bool {
	if o != nil && o.GiftBillingHint != nil {
		return true
	}

	return false
}

// SetGiftBillingHint gets a reference to the given string and assigns it to the GiftBillingHint field.
func (o *Frame) SetGiftBillingHint(v string) {
	o.GiftBillingHint = &v
}

// GetLocale returns the Locale field value if set, zero value otherwise.
func (o *Frame) GetLocale() string {
	if o == nil || o.Locale == nil {
		var ret string
		return ret
	}
	return *o.Locale
}

// GetLocaleOk returns a tuple with the Locale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetLocaleOk() (*string, bool) {
	if o == nil || o.Locale == nil {
		return nil, false
	}
	return o.Locale, true
}

// HasLocale returns a boolean if a field has been set.
func (o *Frame) HasLocale() bool {
	if o != nil && o.Locale != nil {
		return true
	}

	return false
}

// SetLocale gets a reference to the given string and assigns it to the Locale field.
func (o *Frame) SetLocale(v string) {
	o.Locale = &v
}

// GetFrameType returns the FrameType field value if set, zero value otherwise.
func (o *Frame) GetFrameType() string {
	if o == nil || o.FrameType == nil {
		var ret string
		return ret
	}
	return *o.FrameType
}

// GetFrameTypeOk returns a tuple with the FrameType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetFrameTypeOk() (*string, bool) {
	if o == nil || o.FrameType == nil {
		return nil, false
	}
	return o.FrameType, true
}

// HasFrameType returns a boolean if a field has been set.
func (o *Frame) HasFrameType() bool {
	if o != nil && o.FrameType != nil {
		return true
	}

	return false
}

// SetFrameType gets a reference to the given string and assigns it to the FrameType field.
func (o *Frame) SetFrameType(v string) {
	o.FrameType = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Frame) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Frame) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Frame) SetDescription(v string) {
	o.Description = &v
}

// GetRepresentativeAssetId returns the RepresentativeAssetId field value if set, zero value otherwise.
func (o *Frame) GetRepresentativeAssetId() string {
	if o == nil || o.RepresentativeAssetId == nil {
		var ret string
		return ret
	}
	return *o.RepresentativeAssetId
}

// GetRepresentativeAssetIdOk returns a tuple with the RepresentativeAssetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetRepresentativeAssetIdOk() (*string, bool) {
	if o == nil || o.RepresentativeAssetId == nil {
		return nil, false
	}
	return o.RepresentativeAssetId, true
}

// HasRepresentativeAssetId returns a boolean if a field has been set.
func (o *Frame) HasRepresentativeAssetId() bool {
	if o != nil && o.RepresentativeAssetId != nil {
		return true
	}

	return false
}

// SetRepresentativeAssetId gets a reference to the given string and assigns it to the RepresentativeAssetId field.
func (o *Frame) SetRepresentativeAssetId(v string) {
	o.RepresentativeAssetId = &v
}

// GetSortMode returns the SortMode field value if set, zero value otherwise.
func (o *Frame) GetSortMode() string {
	if o == nil || o.SortMode == nil {
		var ret string
		return ret
	}
	return *o.SortMode
}

// GetSortModeOk returns a tuple with the SortMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetSortModeOk() (*string, bool) {
	if o == nil || o.SortMode == nil {
		return nil, false
	}
	return o.SortMode, true
}

// HasSortMode returns a boolean if a field has been set.
func (o *Frame) HasSortMode() bool {
	if o != nil && o.SortMode != nil {
		return true
	}

	return false
}

// SetSortMode gets a reference to the given string and assigns it to the SortMode field.
func (o *Frame) SetSortMode(v string) {
	o.SortMode = &v
}

// GetEmailAddress returns the EmailAddress field value if set, zero value otherwise.
func (o *Frame) GetEmailAddress() string {
	if o == nil || o.EmailAddress == nil {
		var ret string
		return ret
	}
	return *o.EmailAddress
}

// GetEmailAddressOk returns a tuple with the EmailAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetEmailAddressOk() (*string, bool) {
	if o == nil || o.EmailAddress == nil {
		return nil, false
	}
	return o.EmailAddress, true
}

// HasEmailAddress returns a boolean if a field has been set.
func (o *Frame) HasEmailAddress() bool {
	if o != nil && o.EmailAddress != nil {
		return true
	}

	return false
}

// SetEmailAddress gets a reference to the given string and assigns it to the EmailAddress field.
func (o *Frame) SetEmailAddress(v string) {
	o.EmailAddress = &v
}

// GetFeatures returns the Features field value if set, zero value otherwise.
func (o *Frame) GetFeatures() []string {
	if o == nil || o.Features == nil {
		var ret []string
		return ret
	}
	return o.Features
}

// GetFeaturesOk returns a tuple with the Features field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetFeaturesOk() ([]string, bool) {
	if o == nil || o.Features == nil {
		return nil, false
	}
	return o.Features, true
}

// HasFeatures returns a boolean if a field has been set.
func (o *Frame) HasFeatures() bool {
	if o != nil && o.Features != nil {
		return true
	}

	return false
}

// SetFeatures gets a reference to the given []string and assigns it to the Features field.
func (o *Frame) SetFeatures(v []string) {
	o.Features = v
}

// GetVolume returns the Volume field value if set, zero value otherwise.
func (o *Frame) GetVolume() string {
	if o == nil || o.Volume == nil {
		var ret string
		return ret
	}
	return *o.Volume
}

// GetVolumeOk returns a tuple with the Volume field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetVolumeOk() (*string, bool) {
	if o == nil || o.Volume == nil {
		return nil, false
	}
	return o.Volume, true
}

// HasVolume returns a boolean if a field has been set.
func (o *Frame) HasVolume() bool {
	if o != nil && o.Volume != nil {
		return true
	}

	return false
}

// SetVolume gets a reference to the given string and assigns it to the Volume field.
func (o *Frame) SetVolume(v string) {
	o.Volume = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *Frame) GetUser() User {
	if o == nil || o.User == nil {
		var ret User
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetUserOk() (*User, bool) {
	if o == nil || o.User == nil {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *Frame) HasUser() bool {
	if o != nil && o.User != nil {
		return true
	}

	return false
}

// SetUser gets a reference to the given User and assigns it to the User field.
func (o *Frame) SetUser(v User) {
	o.User = &v
}

// GetPlaylists returns the Playlists field value if set, zero value otherwise.
func (o *Frame) GetPlaylists() []string {
	if o == nil || o.Playlists == nil {
		var ret []string
		return ret
	}
	return o.Playlists
}

// GetPlaylistsOk returns a tuple with the Playlists field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetPlaylistsOk() ([]string, bool) {
	if o == nil || o.Playlists == nil {
		return nil, false
	}
	return o.Playlists, true
}

// HasPlaylists returns a boolean if a field has been set.
func (o *Frame) HasPlaylists() bool {
	if o != nil && o.Playlists != nil {
		return true
	}

	return false
}

// SetPlaylists gets a reference to the given []string and assigns it to the Playlists field.
func (o *Frame) SetPlaylists(v []string) {
	o.Playlists = v
}

// GetLastFeedItem returns the LastFeedItem field value if set, zero value otherwise.
func (o *Frame) GetLastFeedItem() FeedItem {
	if o == nil || o.LastFeedItem == nil {
		var ret FeedItem
		return ret
	}
	return *o.LastFeedItem
}

// GetLastFeedItemOk returns a tuple with the LastFeedItem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetLastFeedItemOk() (*FeedItem, bool) {
	if o == nil || o.LastFeedItem == nil {
		return nil, false
	}
	return o.LastFeedItem, true
}

// HasLastFeedItem returns a boolean if a field has been set.
func (o *Frame) HasLastFeedItem() bool {
	if o != nil && o.LastFeedItem != nil {
		return true
	}

	return false
}

// SetLastFeedItem gets a reference to the given FeedItem and assigns it to the LastFeedItem field.
func (o *Frame) SetLastFeedItem(v FeedItem) {
	o.LastFeedItem = &v
}

// GetLastImpression returns the LastImpression field value if set, zero value otherwise.
func (o *Frame) GetLastImpression() Impression {
	if o == nil || o.LastImpression == nil {
		var ret Impression
		return ret
	}
	return *o.LastImpression
}

// GetLastImpressionOk returns a tuple with the LastImpression field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetLastImpressionOk() (*Impression, bool) {
	if o == nil || o.LastImpression == nil {
		return nil, false
	}
	return o.LastImpression, true
}

// HasLastImpression returns a boolean if a field has been set.
func (o *Frame) HasLastImpression() bool {
	if o != nil && o.LastImpression != nil {
		return true
	}

	return false
}

// SetLastImpression gets a reference to the given Impression and assigns it to the LastImpression field.
func (o *Frame) SetLastImpression(v Impression) {
	o.LastImpression = &v
}

// GetRecentAssets returns the RecentAssets field value if set, zero value otherwise.
func (o *Frame) GetRecentAssets() []Asset {
	if o == nil || o.RecentAssets == nil {
		var ret []Asset
		return ret
	}
	return o.RecentAssets
}

// GetRecentAssetsOk returns a tuple with the RecentAssets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetRecentAssetsOk() ([]Asset, bool) {
	if o == nil || o.RecentAssets == nil {
		return nil, false
	}
	return o.RecentAssets, true
}

// HasRecentAssets returns a boolean if a field has been set.
func (o *Frame) HasRecentAssets() bool {
	if o != nil && o.RecentAssets != nil {
		return true
	}

	return false
}

// SetRecentAssets gets a reference to the given []Asset and assigns it to the RecentAssets field.
func (o *Frame) SetRecentAssets(v []Asset) {
	o.RecentAssets = v
}

// GetContributors returns the Contributors field value if set, zero value otherwise.
func (o *Frame) GetContributors() []User {
	if o == nil || o.Contributors == nil {
		var ret []User
		return ret
	}
	return o.Contributors
}

// GetContributorsOk returns a tuple with the Contributors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetContributorsOk() ([]User, bool) {
	if o == nil || o.Contributors == nil {
		return nil, false
	}
	return o.Contributors, true
}

// HasContributors returns a boolean if a field has been set.
func (o *Frame) HasContributors() bool {
	if o != nil && o.Contributors != nil {
		return true
	}

	return false
}

// SetContributors gets a reference to the given []User and assigns it to the Contributors field.
func (o *Frame) SetContributors(v []User) {
	o.Contributors = v
}

// GetFrameEnvironment returns the FrameEnvironment field value if set, zero value otherwise.
func (o *Frame) GetFrameEnvironment() FrameEnvironment {
	if o == nil || o.FrameEnvironment == nil {
		var ret FrameEnvironment
		return ret
	}
	return *o.FrameEnvironment
}

// GetFrameEnvironmentOk returns a tuple with the FrameEnvironment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetFrameEnvironmentOk() (*FrameEnvironment, bool) {
	if o == nil || o.FrameEnvironment == nil {
		return nil, false
	}
	return o.FrameEnvironment, true
}

// HasFrameEnvironment returns a boolean if a field has been set.
func (o *Frame) HasFrameEnvironment() bool {
	if o != nil && o.FrameEnvironment != nil {
		return true
	}

	return false
}

// SetFrameEnvironment gets a reference to the given FrameEnvironment and assigns it to the FrameEnvironment field.
func (o *Frame) SetFrameEnvironment(v FrameEnvironment) {
	o.FrameEnvironment = &v
}

// GetCurrentPrintSet returns the CurrentPrintSet field value if set, zero value otherwise.
func (o *Frame) GetCurrentPrintSet() string {
	if o == nil || o.CurrentPrintSet == nil {
		var ret string
		return ret
	}
	return *o.CurrentPrintSet
}

// GetCurrentPrintSetOk returns a tuple with the CurrentPrintSet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetCurrentPrintSetOk() (*string, bool) {
	if o == nil || o.CurrentPrintSet == nil {
		return nil, false
	}
	return o.CurrentPrintSet, true
}

// HasCurrentPrintSet returns a boolean if a field has been set.
func (o *Frame) HasCurrentPrintSet() bool {
	if o != nil && o.CurrentPrintSet != nil {
		return true
	}

	return false
}

// SetCurrentPrintSet gets a reference to the given string and assigns it to the CurrentPrintSet field.
func (o *Frame) SetCurrentPrintSet(v string) {
	o.CurrentPrintSet = &v
}

// GetFirstPrintSet returns the FirstPrintSet field value if set, zero value otherwise.
func (o *Frame) GetFirstPrintSet() string {
	if o == nil || o.FirstPrintSet == nil {
		var ret string
		return ret
	}
	return *o.FirstPrintSet
}

// GetFirstPrintSetOk returns a tuple with the FirstPrintSet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetFirstPrintSetOk() (*string, bool) {
	if o == nil || o.FirstPrintSet == nil {
		return nil, false
	}
	return o.FirstPrintSet, true
}

// HasFirstPrintSet returns a boolean if a field has been set.
func (o *Frame) HasFirstPrintSet() bool {
	if o != nil && o.FirstPrintSet != nil {
		return true
	}

	return false
}

// SetFirstPrintSet gets a reference to the given string and assigns it to the FirstPrintSet field.
func (o *Frame) SetFirstPrintSet(v string) {
	o.FirstPrintSet = &v
}

// GetChildAlbums returns the ChildAlbums field value if set, zero value otherwise.
func (o *Frame) GetChildAlbums() []string {
	if o == nil || o.ChildAlbums == nil {
		var ret []string
		return ret
	}
	return o.ChildAlbums
}

// GetChildAlbumsOk returns a tuple with the ChildAlbums field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetChildAlbumsOk() ([]string, bool) {
	if o == nil || o.ChildAlbums == nil {
		return nil, false
	}
	return o.ChildAlbums, true
}

// HasChildAlbums returns a boolean if a field has been set.
func (o *Frame) HasChildAlbums() bool {
	if o != nil && o.ChildAlbums != nil {
		return true
	}

	return false
}

// SetChildAlbums gets a reference to the given []string and assigns it to the ChildAlbums field.
func (o *Frame) SetChildAlbums(v []string) {
	o.ChildAlbums = v
}

// GetSmartAdds returns the SmartAdds field value if set, zero value otherwise.
func (o *Frame) GetSmartAdds() []string {
	if o == nil || o.SmartAdds == nil {
		var ret []string
		return ret
	}
	return o.SmartAdds
}

// GetSmartAddsOk returns a tuple with the SmartAdds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Frame) GetSmartAddsOk() ([]string, bool) {
	if o == nil || o.SmartAdds == nil {
		return nil, false
	}
	return o.SmartAdds, true
}

// HasSmartAdds returns a boolean if a field has been set.
func (o *Frame) HasSmartAdds() bool {
	if o != nil && o.SmartAdds != nil {
		return true
	}

	return false
}

// SetSmartAdds gets a reference to the given []string and assigns it to the SmartAdds field.
func (o *Frame) SetSmartAdds(v []string) {
	o.SmartAdds = v
}

func (o Frame) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.UserId != nil {
		toSerialize["user_id"] = o.UserId
	}
	if o.SoftwareVersion != nil {
		toSerialize["software_version"] = o.SoftwareVersion
	}
	if o.BuildVersion != nil {
		toSerialize["build_version"] = o.BuildVersion
	}
	if o.HwAndroidVersion != nil {
		toSerialize["hw_android_version"] = o.HwAndroidVersion
	}
	if o.CreatedAt != nil {
		toSerialize["created_at"] = o.CreatedAt
	}
	if o.UpdatedAt != nil {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if o.HandledAt != nil {
		toSerialize["handled_at"] = o.HandledAt
	}
	if o.DeletedAt != nil {
		toSerialize["deleted_at"] = o.DeletedAt
	}
	if o.UpdatedAtOnClient != nil {
		toSerialize["updated_at_on_client"] = o.UpdatedAtOnClient
	}
	if o.LastImpressionAt != nil {
		toSerialize["last_impression_at"] = o.LastImpressionAt
	}
	if o.Orientation != nil {
		toSerialize["orientation"] = o.Orientation
	}
	if o.AutoBrightness != nil {
		toSerialize["auto_brightness"] = o.AutoBrightness
	}
	if o.MinBrightness != nil {
		toSerialize["min_brightness"] = o.MinBrightness
	}
	if o.MaxBrightness != nil {
		toSerialize["max_brightness"] = o.MaxBrightness
	}
	if o.Brightness != nil {
		toSerialize["brightness"] = o.Brightness
	}
	if o.SenseMotion != nil {
		toSerialize["sense_motion"] = o.SenseMotion
	}
	if o.DefaultSpeed != nil {
		toSerialize["default_speed"] = o.DefaultSpeed
	}
	if o.SlideshowInterval != nil {
		toSerialize["slideshow_interval"] = o.SlideshowInterval
	}
	if o.SlideshowAuto != nil {
		toSerialize["slideshow_auto"] = o.SlideshowAuto
	}
	if o.Digits != nil {
		toSerialize["digits"] = o.Digits
	}
	if o.ContributorTokens != nil {
		toSerialize["contributor_tokens"] = o.ContributorTokens
	}
	if o.HwSerial != nil {
		toSerialize["hw_serial"] = o.HwSerial
	}
	if o.MattingColor != nil {
		toSerialize["matting_color"] = o.MattingColor
	}
	if o.TrimColor != nil {
		toSerialize["trim_color"] = o.TrimColor
	}
	if o.IsHandling != nil {
		toSerialize["is_handling"] = o.IsHandling
	}
	if o.CalibrationsLastModifiedAt != nil {
		toSerialize["calibrations_last_modified_at"] = o.CalibrationsLastModifiedAt
	}
	if o.GesturesOn != nil {
		toSerialize["gestures_on"] = o.GesturesOn
	}
	if o.PortraitPairingOff != nil {
		toSerialize["portrait_pairing_off"] = o.PortraitPairingOff
	}
	if o.LivePhotosOn != nil {
		toSerialize["live_photos_on"] = o.LivePhotosOn
	}
	if o.AutoProcessedPlaylistIds != nil {
		toSerialize["auto_processed_playlist_ids"] = o.AutoProcessedPlaylistIds
	}
	if o.TimeZone != nil {
		toSerialize["time_zone"] = o.TimeZone
	}
	if o.WifiNetwork != nil {
		toSerialize["wifi_network"] = o.WifiNetwork
	}
	if o.ColdBootAt != nil {
		toSerialize["cold_boot_at"] = o.ColdBootAt
	}
	if o.IsCharityWaterFrame != nil {
		toSerialize["is_charity_water_frame"] = o.IsCharityWaterFrame
	}
	if o.NumAssets != nil {
		toSerialize["num_assets"] = o.NumAssets
	}
	if o.ThanksOn != nil {
		toSerialize["thanks_on"] = o.ThanksOn
	}
	if o.FrameQueueUrl != nil {
		toSerialize["frame_queue_url"] = o.FrameQueueUrl
	}
	if o.ClientQueueUrl != nil {
		toSerialize["client_queue_url"] = o.ClientQueueUrl
	}
	if o.ScheduledDisplaySleep != nil {
		toSerialize["scheduled_display_sleep"] = o.ScheduledDisplaySleep
	}
	if o.ScheduledDisplayOnAt != nil {
		toSerialize["scheduled_display_on_at"] = o.ScheduledDisplayOnAt
	}
	if o.ScheduledDisplayOffAt != nil {
		toSerialize["scheduled_display_off_at"] = o.ScheduledDisplayOffAt
	}
	if o.ForcedWifiState != nil {
		toSerialize["forced_wifi_state"] = o.ForcedWifiState
	}
	if o.ForcedWifiRecipientEmail != nil {
		toSerialize["forced_wifi_recipient_email"] = o.ForcedWifiRecipientEmail
	}
	if o.IsAnalogFrame != nil {
		toSerialize["is_analog_frame"] = o.IsAnalogFrame
	}
	if o.ControlType != nil {
		toSerialize["control_type"] = o.ControlType
	}
	if o.DisplayAspectRatio != nil {
		toSerialize["display_aspect_ratio"] = o.DisplayAspectRatio
	}
	if o.HasClaimableGift != nil {
		toSerialize["has_claimable_gift"] = o.HasClaimableGift
	}
	if o.GiftBillingHint != nil {
		toSerialize["gift_billing_hint"] = o.GiftBillingHint
	}
	if o.Locale != nil {
		toSerialize["locale"] = o.Locale
	}
	if o.FrameType != nil {
		toSerialize["frame_type"] = o.FrameType
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.RepresentativeAssetId != nil {
		toSerialize["representative_asset_id"] = o.RepresentativeAssetId
	}
	if o.SortMode != nil {
		toSerialize["sort_mode"] = o.SortMode
	}
	if o.EmailAddress != nil {
		toSerialize["email_address"] = o.EmailAddress
	}
	if o.Features != nil {
		toSerialize["features"] = o.Features
	}
	if o.Volume != nil {
		toSerialize["volume"] = o.Volume
	}
	if o.User != nil {
		toSerialize["user"] = o.User
	}
	if o.Playlists != nil {
		toSerialize["playlists"] = o.Playlists
	}
	if o.LastFeedItem != nil {
		toSerialize["last_feed_item"] = o.LastFeedItem
	}
	if o.LastImpression != nil {
		toSerialize["last_impression"] = o.LastImpression
	}
	if o.RecentAssets != nil {
		toSerialize["recent_assets"] = o.RecentAssets
	}
	if o.Contributors != nil {
		toSerialize["contributors"] = o.Contributors
	}
	if o.FrameEnvironment != nil {
		toSerialize["frame_environment"] = o.FrameEnvironment
	}
	if o.CurrentPrintSet != nil {
		toSerialize["current_print_set"] = o.CurrentPrintSet
	}
	if o.FirstPrintSet != nil {
		toSerialize["first_print_set"] = o.FirstPrintSet
	}
	if o.ChildAlbums != nil {
		toSerialize["child_albums"] = o.ChildAlbums
	}
	if o.SmartAdds != nil {
		toSerialize["smart_adds"] = o.SmartAdds
	}
	return json.Marshal(toSerialize)
}

type NullableFrame struct {
	value *Frame
	isSet bool
}

func (v NullableFrame) Get() *Frame {
	return v.value
}

func (v *NullableFrame) Set(val *Frame) {
	v.value = val
	v.isSet = true
}

func (v NullableFrame) IsSet() bool {
	return v.isSet
}

func (v *NullableFrame) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFrame(val *Frame) *NullableFrame {
	return &NullableFrame{value: val, isSet: true}
}

func (v NullableFrame) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFrame) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


