/*
Aura Frame API - Unofficial

Reverse Engineered API for Aura Frames

API version: 0.0.1
Contact: dave@mudsite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package auraframes

import (
	"encoding/json"
)

// LoginRequest struct for LoginRequest
type LoginRequest struct {
	AppIdentifier string `json:"app_identifier"`
	ClientDeviceId string `json:"client_device_id"`
	IdentifierForVendor string `json:"identifier_for_vendor"`
	Locale string `json:"locale"`
	User LoginRequestUser `json:"user"`
}

// NewLoginRequest instantiates a new LoginRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginRequest(appIdentifier string, clientDeviceId string, identifierForVendor string, locale string, user LoginRequestUser) *LoginRequest {
	this := LoginRequest{}
	this.AppIdentifier = appIdentifier
	this.ClientDeviceId = clientDeviceId
	this.IdentifierForVendor = identifierForVendor
	this.Locale = locale
	this.User = user
	return &this
}

// NewLoginRequestWithDefaults instantiates a new LoginRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginRequestWithDefaults() *LoginRequest {
	this := LoginRequest{}
	return &this
}

// GetAppIdentifier returns the AppIdentifier field value
func (o *LoginRequest) GetAppIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AppIdentifier
}

// GetAppIdentifierOk returns a tuple with the AppIdentifier field value
// and a boolean to check if the value has been set.
func (o *LoginRequest) GetAppIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppIdentifier, true
}

// SetAppIdentifier sets field value
func (o *LoginRequest) SetAppIdentifier(v string) {
	o.AppIdentifier = v
}

// GetClientDeviceId returns the ClientDeviceId field value
func (o *LoginRequest) GetClientDeviceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientDeviceId
}

// GetClientDeviceIdOk returns a tuple with the ClientDeviceId field value
// and a boolean to check if the value has been set.
func (o *LoginRequest) GetClientDeviceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientDeviceId, true
}

// SetClientDeviceId sets field value
func (o *LoginRequest) SetClientDeviceId(v string) {
	o.ClientDeviceId = v
}

// GetIdentifierForVendor returns the IdentifierForVendor field value
func (o *LoginRequest) GetIdentifierForVendor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IdentifierForVendor
}

// GetIdentifierForVendorOk returns a tuple with the IdentifierForVendor field value
// and a boolean to check if the value has been set.
func (o *LoginRequest) GetIdentifierForVendorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IdentifierForVendor, true
}

// SetIdentifierForVendor sets field value
func (o *LoginRequest) SetIdentifierForVendor(v string) {
	o.IdentifierForVendor = v
}

// GetLocale returns the Locale field value
func (o *LoginRequest) GetLocale() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Locale
}

// GetLocaleOk returns a tuple with the Locale field value
// and a boolean to check if the value has been set.
func (o *LoginRequest) GetLocaleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Locale, true
}

// SetLocale sets field value
func (o *LoginRequest) SetLocale(v string) {
	o.Locale = v
}

// GetUser returns the User field value
func (o *LoginRequest) GetUser() LoginRequestUser {
	if o == nil {
		var ret LoginRequestUser
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *LoginRequest) GetUserOk() (*LoginRequestUser, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *LoginRequest) SetUser(v LoginRequestUser) {
	o.User = v
}

func (o LoginRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["app_identifier"] = o.AppIdentifier
	}
	if true {
		toSerialize["client_device_id"] = o.ClientDeviceId
	}
	if true {
		toSerialize["identifier_for_vendor"] = o.IdentifierForVendor
	}
	if true {
		toSerialize["locale"] = o.Locale
	}
	if true {
		toSerialize["user"] = o.User
	}
	return json.Marshal(toSerialize)
}

type NullableLoginRequest struct {
	value *LoginRequest
	isSet bool
}

func (v NullableLoginRequest) Get() *LoginRequest {
	return v.value
}

func (v *NullableLoginRequest) Set(val *LoginRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginRequest(val *LoginRequest) *NullableLoginRequest {
	return &NullableLoginRequest{value: val, isSet: true}
}

func (v NullableLoginRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


