/*
Aura Frame API - Unofficial

Reverse Engineered API for Aura Frames

API version: 0.0.1
Contact: dave@mudsite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package auraframes

import (
	"encoding/json"
)

// LoginRequestUser struct for LoginRequestUser
type LoginRequestUser struct {
	Email string `json:"email"`
	Password string `json:"password"`
}

// NewLoginRequestUser instantiates a new LoginRequestUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginRequestUser(email string, password string) *LoginRequestUser {
	this := LoginRequestUser{}
	this.Email = email
	this.Password = password
	return &this
}

// NewLoginRequestUserWithDefaults instantiates a new LoginRequestUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginRequestUserWithDefaults() *LoginRequestUser {
	this := LoginRequestUser{}
	return &this
}

// GetEmail returns the Email field value
func (o *LoginRequestUser) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *LoginRequestUser) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *LoginRequestUser) SetEmail(v string) {
	o.Email = v
}

// GetPassword returns the Password field value
func (o *LoginRequestUser) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *LoginRequestUser) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *LoginRequestUser) SetPassword(v string) {
	o.Password = v
}

func (o LoginRequestUser) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["email"] = o.Email
	}
	if true {
		toSerialize["password"] = o.Password
	}
	return json.Marshal(toSerialize)
}

type NullableLoginRequestUser struct {
	value *LoginRequestUser
	isSet bool
}

func (v NullableLoginRequestUser) Get() *LoginRequestUser {
	return v.value
}

func (v *NullableLoginRequestUser) Set(val *LoginRequestUser) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginRequestUser) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginRequestUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginRequestUser(val *LoginRequestUser) *NullableLoginRequestUser {
	return &NullableLoginRequestUser{value: val, isSet: true}
}

func (v NullableLoginRequestUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginRequestUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


