/*
Aura Frame API - Unofficial

Reverse Engineered API for Aura Frames

API version: 0.0.1
Contact: dave@mudsite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package auraframes

import (
	"encoding/json"
)

// Asset struct for Asset
type Asset struct {
	Id *string `json:"id,omitempty"`
	UserId *string `json:"user_id,omitempty"`
	ThumbnailUrl *string `json:"thumbnail_url,omitempty"`
	PortraitUrl *string `json:"portrait_url,omitempty"`
	LandscapeUrl *string `json:"landscape_url,omitempty"`
	Landscape1610Url *string `json:"landscape_16_10_url,omitempty"`
	Portrait45Url *string `json:"portrait_4_5_url,omitempty"`
	VideoUrl *string `json:"video_url,omitempty"`
	LandscapeRect *string `json:"landscape_rect,omitempty"`
	PortraitRect *string `json:"portrait_rect,omitempty"`
	UserLandscapeRect *string `json:"user_landscape_rect,omitempty"`
	UserPortraitRect *string `json:"user_portrait_rect,omitempty"`
	AutoLandscape1610Rect *string `json:"auto_landscape_16_10_rect,omitempty"`
	UserLandscape1610Rect *string `json:"user_landscape_16_10_rect,omitempty"`
	AutoPortrait45Rect *string `json:"auto_portrait_4_5_rect,omitempty"`
	UserPortrait45Rect *string `json:"user_portrait_4_5_rect,omitempty"`
	ExifOrientation *string `json:"exif_orientation,omitempty"`
	HandledAt *string `json:"handled_at,omitempty"`
	UploadedAt *string `json:"uploaded_at,omitempty"`
	GoodResolution *bool `json:"good_resolution,omitempty"`
	SourceId *string `json:"source_id,omitempty"`
	DuplicateOfId *string `json:"duplicate_of_id,omitempty"`
	RotationCw *string `json:"rotation_cw,omitempty"`
	LocationName *string `json:"location_name,omitempty"`
	Md5Hash *string `json:"md5_hash,omitempty"`
	IsSubscription *bool `json:"is_subscription,omitempty"`
	GlacieredAt *string `json:"glaciered_at,omitempty"`
	Unglacierable *bool `json:"unglacierable,omitempty"`
	Duration *string `json:"duration,omitempty"`
	LivePhotoOff *string `json:"live_photo_off,omitempty"`
	LocalIdentifier *string `json:"local_identifier,omitempty"`
	CreatedAtOnClient *string `json:"created_at_on_client,omitempty"`
	Selected *bool `json:"selected,omitempty"`
	FileName *string `json:"file_name,omitempty"`
	RawFileName *string `json:"raw_file_name,omitempty"`
	VideoFileName *string `json:"video_file_name,omitempty"`
	Width *string `json:"width,omitempty"`
	Height *string `json:"height,omitempty"`
	TakenAt *string `json:"taken_at,omitempty"`
	HorizontalAccuracy *string `json:"horizontal_accuracy,omitempty"`
	Favorite *bool `json:"favorite,omitempty"`
	Orientation *string `json:"orientation,omitempty"`
	Hdr *bool `json:"hdr,omitempty"`
	Panorama *bool `json:"panorama,omitempty"`
	IsLive *string `json:"is_live,omitempty"`
	BurstId *string `json:"burst_id,omitempty"`
	BurstSelectionTypes *string `json:"burst_selection_types,omitempty"`
	RepresentsBurst *string `json:"represents_burst,omitempty"`
	DataUti *string `json:"data_uti,omitempty"`
	OriginalFileName *string `json:"original_file_name,omitempty"`
	UploadPriority *string `json:"upload_priority,omitempty"`
	IosMediaSubtypes *string `json:"ios_media_subtypes,omitempty"`
	TakenAtUserOverrideAt *string `json:"taken_at_user_override_at,omitempty"`
	DurationUnclipped *string `json:"duration_unclipped,omitempty"`
	VideoClipStart *string `json:"video_clip_start,omitempty"`
	VideoClipExcludesAudio *string `json:"video_clip_excludes_audio,omitempty"`
	VideoClippedByUserAt *string `json:"video_clipped_by_user_at,omitempty"`
	Location *string `json:"location,omitempty"`
	User *User `json:"user,omitempty"`
}

// NewAsset instantiates a new Asset object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAsset() *Asset {
	this := Asset{}
	return &this
}

// NewAssetWithDefaults instantiates a new Asset object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssetWithDefaults() *Asset {
	this := Asset{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Asset) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Asset) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Asset) SetId(v string) {
	o.Id = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *Asset) GetUserId() string {
	if o == nil || o.UserId == nil {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetUserIdOk() (*string, bool) {
	if o == nil || o.UserId == nil {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *Asset) HasUserId() bool {
	if o != nil && o.UserId != nil {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *Asset) SetUserId(v string) {
	o.UserId = &v
}

// GetThumbnailUrl returns the ThumbnailUrl field value if set, zero value otherwise.
func (o *Asset) GetThumbnailUrl() string {
	if o == nil || o.ThumbnailUrl == nil {
		var ret string
		return ret
	}
	return *o.ThumbnailUrl
}

// GetThumbnailUrlOk returns a tuple with the ThumbnailUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetThumbnailUrlOk() (*string, bool) {
	if o == nil || o.ThumbnailUrl == nil {
		return nil, false
	}
	return o.ThumbnailUrl, true
}

// HasThumbnailUrl returns a boolean if a field has been set.
func (o *Asset) HasThumbnailUrl() bool {
	if o != nil && o.ThumbnailUrl != nil {
		return true
	}

	return false
}

// SetThumbnailUrl gets a reference to the given string and assigns it to the ThumbnailUrl field.
func (o *Asset) SetThumbnailUrl(v string) {
	o.ThumbnailUrl = &v
}

// GetPortraitUrl returns the PortraitUrl field value if set, zero value otherwise.
func (o *Asset) GetPortraitUrl() string {
	if o == nil || o.PortraitUrl == nil {
		var ret string
		return ret
	}
	return *o.PortraitUrl
}

// GetPortraitUrlOk returns a tuple with the PortraitUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetPortraitUrlOk() (*string, bool) {
	if o == nil || o.PortraitUrl == nil {
		return nil, false
	}
	return o.PortraitUrl, true
}

// HasPortraitUrl returns a boolean if a field has been set.
func (o *Asset) HasPortraitUrl() bool {
	if o != nil && o.PortraitUrl != nil {
		return true
	}

	return false
}

// SetPortraitUrl gets a reference to the given string and assigns it to the PortraitUrl field.
func (o *Asset) SetPortraitUrl(v string) {
	o.PortraitUrl = &v
}

// GetLandscapeUrl returns the LandscapeUrl field value if set, zero value otherwise.
func (o *Asset) GetLandscapeUrl() string {
	if o == nil || o.LandscapeUrl == nil {
		var ret string
		return ret
	}
	return *o.LandscapeUrl
}

// GetLandscapeUrlOk returns a tuple with the LandscapeUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetLandscapeUrlOk() (*string, bool) {
	if o == nil || o.LandscapeUrl == nil {
		return nil, false
	}
	return o.LandscapeUrl, true
}

// HasLandscapeUrl returns a boolean if a field has been set.
func (o *Asset) HasLandscapeUrl() bool {
	if o != nil && o.LandscapeUrl != nil {
		return true
	}

	return false
}

// SetLandscapeUrl gets a reference to the given string and assigns it to the LandscapeUrl field.
func (o *Asset) SetLandscapeUrl(v string) {
	o.LandscapeUrl = &v
}

// GetLandscape1610Url returns the Landscape1610Url field value if set, zero value otherwise.
func (o *Asset) GetLandscape1610Url() string {
	if o == nil || o.Landscape1610Url == nil {
		var ret string
		return ret
	}
	return *o.Landscape1610Url
}

// GetLandscape1610UrlOk returns a tuple with the Landscape1610Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetLandscape1610UrlOk() (*string, bool) {
	if o == nil || o.Landscape1610Url == nil {
		return nil, false
	}
	return o.Landscape1610Url, true
}

// HasLandscape1610Url returns a boolean if a field has been set.
func (o *Asset) HasLandscape1610Url() bool {
	if o != nil && o.Landscape1610Url != nil {
		return true
	}

	return false
}

// SetLandscape1610Url gets a reference to the given string and assigns it to the Landscape1610Url field.
func (o *Asset) SetLandscape1610Url(v string) {
	o.Landscape1610Url = &v
}

// GetPortrait45Url returns the Portrait45Url field value if set, zero value otherwise.
func (o *Asset) GetPortrait45Url() string {
	if o == nil || o.Portrait45Url == nil {
		var ret string
		return ret
	}
	return *o.Portrait45Url
}

// GetPortrait45UrlOk returns a tuple with the Portrait45Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetPortrait45UrlOk() (*string, bool) {
	if o == nil || o.Portrait45Url == nil {
		return nil, false
	}
	return o.Portrait45Url, true
}

// HasPortrait45Url returns a boolean if a field has been set.
func (o *Asset) HasPortrait45Url() bool {
	if o != nil && o.Portrait45Url != nil {
		return true
	}

	return false
}

// SetPortrait45Url gets a reference to the given string and assigns it to the Portrait45Url field.
func (o *Asset) SetPortrait45Url(v string) {
	o.Portrait45Url = &v
}

// GetVideoUrl returns the VideoUrl field value if set, zero value otherwise.
func (o *Asset) GetVideoUrl() string {
	if o == nil || o.VideoUrl == nil {
		var ret string
		return ret
	}
	return *o.VideoUrl
}

// GetVideoUrlOk returns a tuple with the VideoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetVideoUrlOk() (*string, bool) {
	if o == nil || o.VideoUrl == nil {
		return nil, false
	}
	return o.VideoUrl, true
}

// HasVideoUrl returns a boolean if a field has been set.
func (o *Asset) HasVideoUrl() bool {
	if o != nil && o.VideoUrl != nil {
		return true
	}

	return false
}

// SetVideoUrl gets a reference to the given string and assigns it to the VideoUrl field.
func (o *Asset) SetVideoUrl(v string) {
	o.VideoUrl = &v
}

// GetLandscapeRect returns the LandscapeRect field value if set, zero value otherwise.
func (o *Asset) GetLandscapeRect() string {
	if o == nil || o.LandscapeRect == nil {
		var ret string
		return ret
	}
	return *o.LandscapeRect
}

// GetLandscapeRectOk returns a tuple with the LandscapeRect field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetLandscapeRectOk() (*string, bool) {
	if o == nil || o.LandscapeRect == nil {
		return nil, false
	}
	return o.LandscapeRect, true
}

// HasLandscapeRect returns a boolean if a field has been set.
func (o *Asset) HasLandscapeRect() bool {
	if o != nil && o.LandscapeRect != nil {
		return true
	}

	return false
}

// SetLandscapeRect gets a reference to the given string and assigns it to the LandscapeRect field.
func (o *Asset) SetLandscapeRect(v string) {
	o.LandscapeRect = &v
}

// GetPortraitRect returns the PortraitRect field value if set, zero value otherwise.
func (o *Asset) GetPortraitRect() string {
	if o == nil || o.PortraitRect == nil {
		var ret string
		return ret
	}
	return *o.PortraitRect
}

// GetPortraitRectOk returns a tuple with the PortraitRect field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetPortraitRectOk() (*string, bool) {
	if o == nil || o.PortraitRect == nil {
		return nil, false
	}
	return o.PortraitRect, true
}

// HasPortraitRect returns a boolean if a field has been set.
func (o *Asset) HasPortraitRect() bool {
	if o != nil && o.PortraitRect != nil {
		return true
	}

	return false
}

// SetPortraitRect gets a reference to the given string and assigns it to the PortraitRect field.
func (o *Asset) SetPortraitRect(v string) {
	o.PortraitRect = &v
}

// GetUserLandscapeRect returns the UserLandscapeRect field value if set, zero value otherwise.
func (o *Asset) GetUserLandscapeRect() string {
	if o == nil || o.UserLandscapeRect == nil {
		var ret string
		return ret
	}
	return *o.UserLandscapeRect
}

// GetUserLandscapeRectOk returns a tuple with the UserLandscapeRect field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetUserLandscapeRectOk() (*string, bool) {
	if o == nil || o.UserLandscapeRect == nil {
		return nil, false
	}
	return o.UserLandscapeRect, true
}

// HasUserLandscapeRect returns a boolean if a field has been set.
func (o *Asset) HasUserLandscapeRect() bool {
	if o != nil && o.UserLandscapeRect != nil {
		return true
	}

	return false
}

// SetUserLandscapeRect gets a reference to the given string and assigns it to the UserLandscapeRect field.
func (o *Asset) SetUserLandscapeRect(v string) {
	o.UserLandscapeRect = &v
}

// GetUserPortraitRect returns the UserPortraitRect field value if set, zero value otherwise.
func (o *Asset) GetUserPortraitRect() string {
	if o == nil || o.UserPortraitRect == nil {
		var ret string
		return ret
	}
	return *o.UserPortraitRect
}

// GetUserPortraitRectOk returns a tuple with the UserPortraitRect field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetUserPortraitRectOk() (*string, bool) {
	if o == nil || o.UserPortraitRect == nil {
		return nil, false
	}
	return o.UserPortraitRect, true
}

// HasUserPortraitRect returns a boolean if a field has been set.
func (o *Asset) HasUserPortraitRect() bool {
	if o != nil && o.UserPortraitRect != nil {
		return true
	}

	return false
}

// SetUserPortraitRect gets a reference to the given string and assigns it to the UserPortraitRect field.
func (o *Asset) SetUserPortraitRect(v string) {
	o.UserPortraitRect = &v
}

// GetAutoLandscape1610Rect returns the AutoLandscape1610Rect field value if set, zero value otherwise.
func (o *Asset) GetAutoLandscape1610Rect() string {
	if o == nil || o.AutoLandscape1610Rect == nil {
		var ret string
		return ret
	}
	return *o.AutoLandscape1610Rect
}

// GetAutoLandscape1610RectOk returns a tuple with the AutoLandscape1610Rect field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetAutoLandscape1610RectOk() (*string, bool) {
	if o == nil || o.AutoLandscape1610Rect == nil {
		return nil, false
	}
	return o.AutoLandscape1610Rect, true
}

// HasAutoLandscape1610Rect returns a boolean if a field has been set.
func (o *Asset) HasAutoLandscape1610Rect() bool {
	if o != nil && o.AutoLandscape1610Rect != nil {
		return true
	}

	return false
}

// SetAutoLandscape1610Rect gets a reference to the given string and assigns it to the AutoLandscape1610Rect field.
func (o *Asset) SetAutoLandscape1610Rect(v string) {
	o.AutoLandscape1610Rect = &v
}

// GetUserLandscape1610Rect returns the UserLandscape1610Rect field value if set, zero value otherwise.
func (o *Asset) GetUserLandscape1610Rect() string {
	if o == nil || o.UserLandscape1610Rect == nil {
		var ret string
		return ret
	}
	return *o.UserLandscape1610Rect
}

// GetUserLandscape1610RectOk returns a tuple with the UserLandscape1610Rect field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetUserLandscape1610RectOk() (*string, bool) {
	if o == nil || o.UserLandscape1610Rect == nil {
		return nil, false
	}
	return o.UserLandscape1610Rect, true
}

// HasUserLandscape1610Rect returns a boolean if a field has been set.
func (o *Asset) HasUserLandscape1610Rect() bool {
	if o != nil && o.UserLandscape1610Rect != nil {
		return true
	}

	return false
}

// SetUserLandscape1610Rect gets a reference to the given string and assigns it to the UserLandscape1610Rect field.
func (o *Asset) SetUserLandscape1610Rect(v string) {
	o.UserLandscape1610Rect = &v
}

// GetAutoPortrait45Rect returns the AutoPortrait45Rect field value if set, zero value otherwise.
func (o *Asset) GetAutoPortrait45Rect() string {
	if o == nil || o.AutoPortrait45Rect == nil {
		var ret string
		return ret
	}
	return *o.AutoPortrait45Rect
}

// GetAutoPortrait45RectOk returns a tuple with the AutoPortrait45Rect field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetAutoPortrait45RectOk() (*string, bool) {
	if o == nil || o.AutoPortrait45Rect == nil {
		return nil, false
	}
	return o.AutoPortrait45Rect, true
}

// HasAutoPortrait45Rect returns a boolean if a field has been set.
func (o *Asset) HasAutoPortrait45Rect() bool {
	if o != nil && o.AutoPortrait45Rect != nil {
		return true
	}

	return false
}

// SetAutoPortrait45Rect gets a reference to the given string and assigns it to the AutoPortrait45Rect field.
func (o *Asset) SetAutoPortrait45Rect(v string) {
	o.AutoPortrait45Rect = &v
}

// GetUserPortrait45Rect returns the UserPortrait45Rect field value if set, zero value otherwise.
func (o *Asset) GetUserPortrait45Rect() string {
	if o == nil || o.UserPortrait45Rect == nil {
		var ret string
		return ret
	}
	return *o.UserPortrait45Rect
}

// GetUserPortrait45RectOk returns a tuple with the UserPortrait45Rect field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetUserPortrait45RectOk() (*string, bool) {
	if o == nil || o.UserPortrait45Rect == nil {
		return nil, false
	}
	return o.UserPortrait45Rect, true
}

// HasUserPortrait45Rect returns a boolean if a field has been set.
func (o *Asset) HasUserPortrait45Rect() bool {
	if o != nil && o.UserPortrait45Rect != nil {
		return true
	}

	return false
}

// SetUserPortrait45Rect gets a reference to the given string and assigns it to the UserPortrait45Rect field.
func (o *Asset) SetUserPortrait45Rect(v string) {
	o.UserPortrait45Rect = &v
}

// GetExifOrientation returns the ExifOrientation field value if set, zero value otherwise.
func (o *Asset) GetExifOrientation() string {
	if o == nil || o.ExifOrientation == nil {
		var ret string
		return ret
	}
	return *o.ExifOrientation
}

// GetExifOrientationOk returns a tuple with the ExifOrientation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetExifOrientationOk() (*string, bool) {
	if o == nil || o.ExifOrientation == nil {
		return nil, false
	}
	return o.ExifOrientation, true
}

// HasExifOrientation returns a boolean if a field has been set.
func (o *Asset) HasExifOrientation() bool {
	if o != nil && o.ExifOrientation != nil {
		return true
	}

	return false
}

// SetExifOrientation gets a reference to the given string and assigns it to the ExifOrientation field.
func (o *Asset) SetExifOrientation(v string) {
	o.ExifOrientation = &v
}

// GetHandledAt returns the HandledAt field value if set, zero value otherwise.
func (o *Asset) GetHandledAt() string {
	if o == nil || o.HandledAt == nil {
		var ret string
		return ret
	}
	return *o.HandledAt
}

// GetHandledAtOk returns a tuple with the HandledAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetHandledAtOk() (*string, bool) {
	if o == nil || o.HandledAt == nil {
		return nil, false
	}
	return o.HandledAt, true
}

// HasHandledAt returns a boolean if a field has been set.
func (o *Asset) HasHandledAt() bool {
	if o != nil && o.HandledAt != nil {
		return true
	}

	return false
}

// SetHandledAt gets a reference to the given string and assigns it to the HandledAt field.
func (o *Asset) SetHandledAt(v string) {
	o.HandledAt = &v
}

// GetUploadedAt returns the UploadedAt field value if set, zero value otherwise.
func (o *Asset) GetUploadedAt() string {
	if o == nil || o.UploadedAt == nil {
		var ret string
		return ret
	}
	return *o.UploadedAt
}

// GetUploadedAtOk returns a tuple with the UploadedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetUploadedAtOk() (*string, bool) {
	if o == nil || o.UploadedAt == nil {
		return nil, false
	}
	return o.UploadedAt, true
}

// HasUploadedAt returns a boolean if a field has been set.
func (o *Asset) HasUploadedAt() bool {
	if o != nil && o.UploadedAt != nil {
		return true
	}

	return false
}

// SetUploadedAt gets a reference to the given string and assigns it to the UploadedAt field.
func (o *Asset) SetUploadedAt(v string) {
	o.UploadedAt = &v
}

// GetGoodResolution returns the GoodResolution field value if set, zero value otherwise.
func (o *Asset) GetGoodResolution() bool {
	if o == nil || o.GoodResolution == nil {
		var ret bool
		return ret
	}
	return *o.GoodResolution
}

// GetGoodResolutionOk returns a tuple with the GoodResolution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetGoodResolutionOk() (*bool, bool) {
	if o == nil || o.GoodResolution == nil {
		return nil, false
	}
	return o.GoodResolution, true
}

// HasGoodResolution returns a boolean if a field has been set.
func (o *Asset) HasGoodResolution() bool {
	if o != nil && o.GoodResolution != nil {
		return true
	}

	return false
}

// SetGoodResolution gets a reference to the given bool and assigns it to the GoodResolution field.
func (o *Asset) SetGoodResolution(v bool) {
	o.GoodResolution = &v
}

// GetSourceId returns the SourceId field value if set, zero value otherwise.
func (o *Asset) GetSourceId() string {
	if o == nil || o.SourceId == nil {
		var ret string
		return ret
	}
	return *o.SourceId
}

// GetSourceIdOk returns a tuple with the SourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetSourceIdOk() (*string, bool) {
	if o == nil || o.SourceId == nil {
		return nil, false
	}
	return o.SourceId, true
}

// HasSourceId returns a boolean if a field has been set.
func (o *Asset) HasSourceId() bool {
	if o != nil && o.SourceId != nil {
		return true
	}

	return false
}

// SetSourceId gets a reference to the given string and assigns it to the SourceId field.
func (o *Asset) SetSourceId(v string) {
	o.SourceId = &v
}

// GetDuplicateOfId returns the DuplicateOfId field value if set, zero value otherwise.
func (o *Asset) GetDuplicateOfId() string {
	if o == nil || o.DuplicateOfId == nil {
		var ret string
		return ret
	}
	return *o.DuplicateOfId
}

// GetDuplicateOfIdOk returns a tuple with the DuplicateOfId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetDuplicateOfIdOk() (*string, bool) {
	if o == nil || o.DuplicateOfId == nil {
		return nil, false
	}
	return o.DuplicateOfId, true
}

// HasDuplicateOfId returns a boolean if a field has been set.
func (o *Asset) HasDuplicateOfId() bool {
	if o != nil && o.DuplicateOfId != nil {
		return true
	}

	return false
}

// SetDuplicateOfId gets a reference to the given string and assigns it to the DuplicateOfId field.
func (o *Asset) SetDuplicateOfId(v string) {
	o.DuplicateOfId = &v
}

// GetRotationCw returns the RotationCw field value if set, zero value otherwise.
func (o *Asset) GetRotationCw() string {
	if o == nil || o.RotationCw == nil {
		var ret string
		return ret
	}
	return *o.RotationCw
}

// GetRotationCwOk returns a tuple with the RotationCw field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetRotationCwOk() (*string, bool) {
	if o == nil || o.RotationCw == nil {
		return nil, false
	}
	return o.RotationCw, true
}

// HasRotationCw returns a boolean if a field has been set.
func (o *Asset) HasRotationCw() bool {
	if o != nil && o.RotationCw != nil {
		return true
	}

	return false
}

// SetRotationCw gets a reference to the given string and assigns it to the RotationCw field.
func (o *Asset) SetRotationCw(v string) {
	o.RotationCw = &v
}

// GetLocationName returns the LocationName field value if set, zero value otherwise.
func (o *Asset) GetLocationName() string {
	if o == nil || o.LocationName == nil {
		var ret string
		return ret
	}
	return *o.LocationName
}

// GetLocationNameOk returns a tuple with the LocationName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetLocationNameOk() (*string, bool) {
	if o == nil || o.LocationName == nil {
		return nil, false
	}
	return o.LocationName, true
}

// HasLocationName returns a boolean if a field has been set.
func (o *Asset) HasLocationName() bool {
	if o != nil && o.LocationName != nil {
		return true
	}

	return false
}

// SetLocationName gets a reference to the given string and assigns it to the LocationName field.
func (o *Asset) SetLocationName(v string) {
	o.LocationName = &v
}

// GetMd5Hash returns the Md5Hash field value if set, zero value otherwise.
func (o *Asset) GetMd5Hash() string {
	if o == nil || o.Md5Hash == nil {
		var ret string
		return ret
	}
	return *o.Md5Hash
}

// GetMd5HashOk returns a tuple with the Md5Hash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetMd5HashOk() (*string, bool) {
	if o == nil || o.Md5Hash == nil {
		return nil, false
	}
	return o.Md5Hash, true
}

// HasMd5Hash returns a boolean if a field has been set.
func (o *Asset) HasMd5Hash() bool {
	if o != nil && o.Md5Hash != nil {
		return true
	}

	return false
}

// SetMd5Hash gets a reference to the given string and assigns it to the Md5Hash field.
func (o *Asset) SetMd5Hash(v string) {
	o.Md5Hash = &v
}

// GetIsSubscription returns the IsSubscription field value if set, zero value otherwise.
func (o *Asset) GetIsSubscription() bool {
	if o == nil || o.IsSubscription == nil {
		var ret bool
		return ret
	}
	return *o.IsSubscription
}

// GetIsSubscriptionOk returns a tuple with the IsSubscription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetIsSubscriptionOk() (*bool, bool) {
	if o == nil || o.IsSubscription == nil {
		return nil, false
	}
	return o.IsSubscription, true
}

// HasIsSubscription returns a boolean if a field has been set.
func (o *Asset) HasIsSubscription() bool {
	if o != nil && o.IsSubscription != nil {
		return true
	}

	return false
}

// SetIsSubscription gets a reference to the given bool and assigns it to the IsSubscription field.
func (o *Asset) SetIsSubscription(v bool) {
	o.IsSubscription = &v
}

// GetGlacieredAt returns the GlacieredAt field value if set, zero value otherwise.
func (o *Asset) GetGlacieredAt() string {
	if o == nil || o.GlacieredAt == nil {
		var ret string
		return ret
	}
	return *o.GlacieredAt
}

// GetGlacieredAtOk returns a tuple with the GlacieredAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetGlacieredAtOk() (*string, bool) {
	if o == nil || o.GlacieredAt == nil {
		return nil, false
	}
	return o.GlacieredAt, true
}

// HasGlacieredAt returns a boolean if a field has been set.
func (o *Asset) HasGlacieredAt() bool {
	if o != nil && o.GlacieredAt != nil {
		return true
	}

	return false
}

// SetGlacieredAt gets a reference to the given string and assigns it to the GlacieredAt field.
func (o *Asset) SetGlacieredAt(v string) {
	o.GlacieredAt = &v
}

// GetUnglacierable returns the Unglacierable field value if set, zero value otherwise.
func (o *Asset) GetUnglacierable() bool {
	if o == nil || o.Unglacierable == nil {
		var ret bool
		return ret
	}
	return *o.Unglacierable
}

// GetUnglacierableOk returns a tuple with the Unglacierable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetUnglacierableOk() (*bool, bool) {
	if o == nil || o.Unglacierable == nil {
		return nil, false
	}
	return o.Unglacierable, true
}

// HasUnglacierable returns a boolean if a field has been set.
func (o *Asset) HasUnglacierable() bool {
	if o != nil && o.Unglacierable != nil {
		return true
	}

	return false
}

// SetUnglacierable gets a reference to the given bool and assigns it to the Unglacierable field.
func (o *Asset) SetUnglacierable(v bool) {
	o.Unglacierable = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *Asset) GetDuration() string {
	if o == nil || o.Duration == nil {
		var ret string
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetDurationOk() (*string, bool) {
	if o == nil || o.Duration == nil {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *Asset) HasDuration() bool {
	if o != nil && o.Duration != nil {
		return true
	}

	return false
}

// SetDuration gets a reference to the given string and assigns it to the Duration field.
func (o *Asset) SetDuration(v string) {
	o.Duration = &v
}

// GetLivePhotoOff returns the LivePhotoOff field value if set, zero value otherwise.
func (o *Asset) GetLivePhotoOff() string {
	if o == nil || o.LivePhotoOff == nil {
		var ret string
		return ret
	}
	return *o.LivePhotoOff
}

// GetLivePhotoOffOk returns a tuple with the LivePhotoOff field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetLivePhotoOffOk() (*string, bool) {
	if o == nil || o.LivePhotoOff == nil {
		return nil, false
	}
	return o.LivePhotoOff, true
}

// HasLivePhotoOff returns a boolean if a field has been set.
func (o *Asset) HasLivePhotoOff() bool {
	if o != nil && o.LivePhotoOff != nil {
		return true
	}

	return false
}

// SetLivePhotoOff gets a reference to the given string and assigns it to the LivePhotoOff field.
func (o *Asset) SetLivePhotoOff(v string) {
	o.LivePhotoOff = &v
}

// GetLocalIdentifier returns the LocalIdentifier field value if set, zero value otherwise.
func (o *Asset) GetLocalIdentifier() string {
	if o == nil || o.LocalIdentifier == nil {
		var ret string
		return ret
	}
	return *o.LocalIdentifier
}

// GetLocalIdentifierOk returns a tuple with the LocalIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetLocalIdentifierOk() (*string, bool) {
	if o == nil || o.LocalIdentifier == nil {
		return nil, false
	}
	return o.LocalIdentifier, true
}

// HasLocalIdentifier returns a boolean if a field has been set.
func (o *Asset) HasLocalIdentifier() bool {
	if o != nil && o.LocalIdentifier != nil {
		return true
	}

	return false
}

// SetLocalIdentifier gets a reference to the given string and assigns it to the LocalIdentifier field.
func (o *Asset) SetLocalIdentifier(v string) {
	o.LocalIdentifier = &v
}

// GetCreatedAtOnClient returns the CreatedAtOnClient field value if set, zero value otherwise.
func (o *Asset) GetCreatedAtOnClient() string {
	if o == nil || o.CreatedAtOnClient == nil {
		var ret string
		return ret
	}
	return *o.CreatedAtOnClient
}

// GetCreatedAtOnClientOk returns a tuple with the CreatedAtOnClient field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetCreatedAtOnClientOk() (*string, bool) {
	if o == nil || o.CreatedAtOnClient == nil {
		return nil, false
	}
	return o.CreatedAtOnClient, true
}

// HasCreatedAtOnClient returns a boolean if a field has been set.
func (o *Asset) HasCreatedAtOnClient() bool {
	if o != nil && o.CreatedAtOnClient != nil {
		return true
	}

	return false
}

// SetCreatedAtOnClient gets a reference to the given string and assigns it to the CreatedAtOnClient field.
func (o *Asset) SetCreatedAtOnClient(v string) {
	o.CreatedAtOnClient = &v
}

// GetSelected returns the Selected field value if set, zero value otherwise.
func (o *Asset) GetSelected() bool {
	if o == nil || o.Selected == nil {
		var ret bool
		return ret
	}
	return *o.Selected
}

// GetSelectedOk returns a tuple with the Selected field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetSelectedOk() (*bool, bool) {
	if o == nil || o.Selected == nil {
		return nil, false
	}
	return o.Selected, true
}

// HasSelected returns a boolean if a field has been set.
func (o *Asset) HasSelected() bool {
	if o != nil && o.Selected != nil {
		return true
	}

	return false
}

// SetSelected gets a reference to the given bool and assigns it to the Selected field.
func (o *Asset) SetSelected(v bool) {
	o.Selected = &v
}

// GetFileName returns the FileName field value if set, zero value otherwise.
func (o *Asset) GetFileName() string {
	if o == nil || o.FileName == nil {
		var ret string
		return ret
	}
	return *o.FileName
}

// GetFileNameOk returns a tuple with the FileName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetFileNameOk() (*string, bool) {
	if o == nil || o.FileName == nil {
		return nil, false
	}
	return o.FileName, true
}

// HasFileName returns a boolean if a field has been set.
func (o *Asset) HasFileName() bool {
	if o != nil && o.FileName != nil {
		return true
	}

	return false
}

// SetFileName gets a reference to the given string and assigns it to the FileName field.
func (o *Asset) SetFileName(v string) {
	o.FileName = &v
}

// GetRawFileName returns the RawFileName field value if set, zero value otherwise.
func (o *Asset) GetRawFileName() string {
	if o == nil || o.RawFileName == nil {
		var ret string
		return ret
	}
	return *o.RawFileName
}

// GetRawFileNameOk returns a tuple with the RawFileName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetRawFileNameOk() (*string, bool) {
	if o == nil || o.RawFileName == nil {
		return nil, false
	}
	return o.RawFileName, true
}

// HasRawFileName returns a boolean if a field has been set.
func (o *Asset) HasRawFileName() bool {
	if o != nil && o.RawFileName != nil {
		return true
	}

	return false
}

// SetRawFileName gets a reference to the given string and assigns it to the RawFileName field.
func (o *Asset) SetRawFileName(v string) {
	o.RawFileName = &v
}

// GetVideoFileName returns the VideoFileName field value if set, zero value otherwise.
func (o *Asset) GetVideoFileName() string {
	if o == nil || o.VideoFileName == nil {
		var ret string
		return ret
	}
	return *o.VideoFileName
}

// GetVideoFileNameOk returns a tuple with the VideoFileName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetVideoFileNameOk() (*string, bool) {
	if o == nil || o.VideoFileName == nil {
		return nil, false
	}
	return o.VideoFileName, true
}

// HasVideoFileName returns a boolean if a field has been set.
func (o *Asset) HasVideoFileName() bool {
	if o != nil && o.VideoFileName != nil {
		return true
	}

	return false
}

// SetVideoFileName gets a reference to the given string and assigns it to the VideoFileName field.
func (o *Asset) SetVideoFileName(v string) {
	o.VideoFileName = &v
}

// GetWidth returns the Width field value if set, zero value otherwise.
func (o *Asset) GetWidth() string {
	if o == nil || o.Width == nil {
		var ret string
		return ret
	}
	return *o.Width
}

// GetWidthOk returns a tuple with the Width field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetWidthOk() (*string, bool) {
	if o == nil || o.Width == nil {
		return nil, false
	}
	return o.Width, true
}

// HasWidth returns a boolean if a field has been set.
func (o *Asset) HasWidth() bool {
	if o != nil && o.Width != nil {
		return true
	}

	return false
}

// SetWidth gets a reference to the given string and assigns it to the Width field.
func (o *Asset) SetWidth(v string) {
	o.Width = &v
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *Asset) GetHeight() string {
	if o == nil || o.Height == nil {
		var ret string
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetHeightOk() (*string, bool) {
	if o == nil || o.Height == nil {
		return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *Asset) HasHeight() bool {
	if o != nil && o.Height != nil {
		return true
	}

	return false
}

// SetHeight gets a reference to the given string and assigns it to the Height field.
func (o *Asset) SetHeight(v string) {
	o.Height = &v
}

// GetTakenAt returns the TakenAt field value if set, zero value otherwise.
func (o *Asset) GetTakenAt() string {
	if o == nil || o.TakenAt == nil {
		var ret string
		return ret
	}
	return *o.TakenAt
}

// GetTakenAtOk returns a tuple with the TakenAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetTakenAtOk() (*string, bool) {
	if o == nil || o.TakenAt == nil {
		return nil, false
	}
	return o.TakenAt, true
}

// HasTakenAt returns a boolean if a field has been set.
func (o *Asset) HasTakenAt() bool {
	if o != nil && o.TakenAt != nil {
		return true
	}

	return false
}

// SetTakenAt gets a reference to the given string and assigns it to the TakenAt field.
func (o *Asset) SetTakenAt(v string) {
	o.TakenAt = &v
}

// GetHorizontalAccuracy returns the HorizontalAccuracy field value if set, zero value otherwise.
func (o *Asset) GetHorizontalAccuracy() string {
	if o == nil || o.HorizontalAccuracy == nil {
		var ret string
		return ret
	}
	return *o.HorizontalAccuracy
}

// GetHorizontalAccuracyOk returns a tuple with the HorizontalAccuracy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetHorizontalAccuracyOk() (*string, bool) {
	if o == nil || o.HorizontalAccuracy == nil {
		return nil, false
	}
	return o.HorizontalAccuracy, true
}

// HasHorizontalAccuracy returns a boolean if a field has been set.
func (o *Asset) HasHorizontalAccuracy() bool {
	if o != nil && o.HorizontalAccuracy != nil {
		return true
	}

	return false
}

// SetHorizontalAccuracy gets a reference to the given string and assigns it to the HorizontalAccuracy field.
func (o *Asset) SetHorizontalAccuracy(v string) {
	o.HorizontalAccuracy = &v
}

// GetFavorite returns the Favorite field value if set, zero value otherwise.
func (o *Asset) GetFavorite() bool {
	if o == nil || o.Favorite == nil {
		var ret bool
		return ret
	}
	return *o.Favorite
}

// GetFavoriteOk returns a tuple with the Favorite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetFavoriteOk() (*bool, bool) {
	if o == nil || o.Favorite == nil {
		return nil, false
	}
	return o.Favorite, true
}

// HasFavorite returns a boolean if a field has been set.
func (o *Asset) HasFavorite() bool {
	if o != nil && o.Favorite != nil {
		return true
	}

	return false
}

// SetFavorite gets a reference to the given bool and assigns it to the Favorite field.
func (o *Asset) SetFavorite(v bool) {
	o.Favorite = &v
}

// GetOrientation returns the Orientation field value if set, zero value otherwise.
func (o *Asset) GetOrientation() string {
	if o == nil || o.Orientation == nil {
		var ret string
		return ret
	}
	return *o.Orientation
}

// GetOrientationOk returns a tuple with the Orientation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetOrientationOk() (*string, bool) {
	if o == nil || o.Orientation == nil {
		return nil, false
	}
	return o.Orientation, true
}

// HasOrientation returns a boolean if a field has been set.
func (o *Asset) HasOrientation() bool {
	if o != nil && o.Orientation != nil {
		return true
	}

	return false
}

// SetOrientation gets a reference to the given string and assigns it to the Orientation field.
func (o *Asset) SetOrientation(v string) {
	o.Orientation = &v
}

// GetHdr returns the Hdr field value if set, zero value otherwise.
func (o *Asset) GetHdr() bool {
	if o == nil || o.Hdr == nil {
		var ret bool
		return ret
	}
	return *o.Hdr
}

// GetHdrOk returns a tuple with the Hdr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetHdrOk() (*bool, bool) {
	if o == nil || o.Hdr == nil {
		return nil, false
	}
	return o.Hdr, true
}

// HasHdr returns a boolean if a field has been set.
func (o *Asset) HasHdr() bool {
	if o != nil && o.Hdr != nil {
		return true
	}

	return false
}

// SetHdr gets a reference to the given bool and assigns it to the Hdr field.
func (o *Asset) SetHdr(v bool) {
	o.Hdr = &v
}

// GetPanorama returns the Panorama field value if set, zero value otherwise.
func (o *Asset) GetPanorama() bool {
	if o == nil || o.Panorama == nil {
		var ret bool
		return ret
	}
	return *o.Panorama
}

// GetPanoramaOk returns a tuple with the Panorama field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetPanoramaOk() (*bool, bool) {
	if o == nil || o.Panorama == nil {
		return nil, false
	}
	return o.Panorama, true
}

// HasPanorama returns a boolean if a field has been set.
func (o *Asset) HasPanorama() bool {
	if o != nil && o.Panorama != nil {
		return true
	}

	return false
}

// SetPanorama gets a reference to the given bool and assigns it to the Panorama field.
func (o *Asset) SetPanorama(v bool) {
	o.Panorama = &v
}

// GetIsLive returns the IsLive field value if set, zero value otherwise.
func (o *Asset) GetIsLive() string {
	if o == nil || o.IsLive == nil {
		var ret string
		return ret
	}
	return *o.IsLive
}

// GetIsLiveOk returns a tuple with the IsLive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetIsLiveOk() (*string, bool) {
	if o == nil || o.IsLive == nil {
		return nil, false
	}
	return o.IsLive, true
}

// HasIsLive returns a boolean if a field has been set.
func (o *Asset) HasIsLive() bool {
	if o != nil && o.IsLive != nil {
		return true
	}

	return false
}

// SetIsLive gets a reference to the given string and assigns it to the IsLive field.
func (o *Asset) SetIsLive(v string) {
	o.IsLive = &v
}

// GetBurstId returns the BurstId field value if set, zero value otherwise.
func (o *Asset) GetBurstId() string {
	if o == nil || o.BurstId == nil {
		var ret string
		return ret
	}
	return *o.BurstId
}

// GetBurstIdOk returns a tuple with the BurstId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetBurstIdOk() (*string, bool) {
	if o == nil || o.BurstId == nil {
		return nil, false
	}
	return o.BurstId, true
}

// HasBurstId returns a boolean if a field has been set.
func (o *Asset) HasBurstId() bool {
	if o != nil && o.BurstId != nil {
		return true
	}

	return false
}

// SetBurstId gets a reference to the given string and assigns it to the BurstId field.
func (o *Asset) SetBurstId(v string) {
	o.BurstId = &v
}

// GetBurstSelectionTypes returns the BurstSelectionTypes field value if set, zero value otherwise.
func (o *Asset) GetBurstSelectionTypes() string {
	if o == nil || o.BurstSelectionTypes == nil {
		var ret string
		return ret
	}
	return *o.BurstSelectionTypes
}

// GetBurstSelectionTypesOk returns a tuple with the BurstSelectionTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetBurstSelectionTypesOk() (*string, bool) {
	if o == nil || o.BurstSelectionTypes == nil {
		return nil, false
	}
	return o.BurstSelectionTypes, true
}

// HasBurstSelectionTypes returns a boolean if a field has been set.
func (o *Asset) HasBurstSelectionTypes() bool {
	if o != nil && o.BurstSelectionTypes != nil {
		return true
	}

	return false
}

// SetBurstSelectionTypes gets a reference to the given string and assigns it to the BurstSelectionTypes field.
func (o *Asset) SetBurstSelectionTypes(v string) {
	o.BurstSelectionTypes = &v
}

// GetRepresentsBurst returns the RepresentsBurst field value if set, zero value otherwise.
func (o *Asset) GetRepresentsBurst() string {
	if o == nil || o.RepresentsBurst == nil {
		var ret string
		return ret
	}
	return *o.RepresentsBurst
}

// GetRepresentsBurstOk returns a tuple with the RepresentsBurst field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetRepresentsBurstOk() (*string, bool) {
	if o == nil || o.RepresentsBurst == nil {
		return nil, false
	}
	return o.RepresentsBurst, true
}

// HasRepresentsBurst returns a boolean if a field has been set.
func (o *Asset) HasRepresentsBurst() bool {
	if o != nil && o.RepresentsBurst != nil {
		return true
	}

	return false
}

// SetRepresentsBurst gets a reference to the given string and assigns it to the RepresentsBurst field.
func (o *Asset) SetRepresentsBurst(v string) {
	o.RepresentsBurst = &v
}

// GetDataUti returns the DataUti field value if set, zero value otherwise.
func (o *Asset) GetDataUti() string {
	if o == nil || o.DataUti == nil {
		var ret string
		return ret
	}
	return *o.DataUti
}

// GetDataUtiOk returns a tuple with the DataUti field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetDataUtiOk() (*string, bool) {
	if o == nil || o.DataUti == nil {
		return nil, false
	}
	return o.DataUti, true
}

// HasDataUti returns a boolean if a field has been set.
func (o *Asset) HasDataUti() bool {
	if o != nil && o.DataUti != nil {
		return true
	}

	return false
}

// SetDataUti gets a reference to the given string and assigns it to the DataUti field.
func (o *Asset) SetDataUti(v string) {
	o.DataUti = &v
}

// GetOriginalFileName returns the OriginalFileName field value if set, zero value otherwise.
func (o *Asset) GetOriginalFileName() string {
	if o == nil || o.OriginalFileName == nil {
		var ret string
		return ret
	}
	return *o.OriginalFileName
}

// GetOriginalFileNameOk returns a tuple with the OriginalFileName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetOriginalFileNameOk() (*string, bool) {
	if o == nil || o.OriginalFileName == nil {
		return nil, false
	}
	return o.OriginalFileName, true
}

// HasOriginalFileName returns a boolean if a field has been set.
func (o *Asset) HasOriginalFileName() bool {
	if o != nil && o.OriginalFileName != nil {
		return true
	}

	return false
}

// SetOriginalFileName gets a reference to the given string and assigns it to the OriginalFileName field.
func (o *Asset) SetOriginalFileName(v string) {
	o.OriginalFileName = &v
}

// GetUploadPriority returns the UploadPriority field value if set, zero value otherwise.
func (o *Asset) GetUploadPriority() string {
	if o == nil || o.UploadPriority == nil {
		var ret string
		return ret
	}
	return *o.UploadPriority
}

// GetUploadPriorityOk returns a tuple with the UploadPriority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetUploadPriorityOk() (*string, bool) {
	if o == nil || o.UploadPriority == nil {
		return nil, false
	}
	return o.UploadPriority, true
}

// HasUploadPriority returns a boolean if a field has been set.
func (o *Asset) HasUploadPriority() bool {
	if o != nil && o.UploadPriority != nil {
		return true
	}

	return false
}

// SetUploadPriority gets a reference to the given string and assigns it to the UploadPriority field.
func (o *Asset) SetUploadPriority(v string) {
	o.UploadPriority = &v
}

// GetIosMediaSubtypes returns the IosMediaSubtypes field value if set, zero value otherwise.
func (o *Asset) GetIosMediaSubtypes() string {
	if o == nil || o.IosMediaSubtypes == nil {
		var ret string
		return ret
	}
	return *o.IosMediaSubtypes
}

// GetIosMediaSubtypesOk returns a tuple with the IosMediaSubtypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetIosMediaSubtypesOk() (*string, bool) {
	if o == nil || o.IosMediaSubtypes == nil {
		return nil, false
	}
	return o.IosMediaSubtypes, true
}

// HasIosMediaSubtypes returns a boolean if a field has been set.
func (o *Asset) HasIosMediaSubtypes() bool {
	if o != nil && o.IosMediaSubtypes != nil {
		return true
	}

	return false
}

// SetIosMediaSubtypes gets a reference to the given string and assigns it to the IosMediaSubtypes field.
func (o *Asset) SetIosMediaSubtypes(v string) {
	o.IosMediaSubtypes = &v
}

// GetTakenAtUserOverrideAt returns the TakenAtUserOverrideAt field value if set, zero value otherwise.
func (o *Asset) GetTakenAtUserOverrideAt() string {
	if o == nil || o.TakenAtUserOverrideAt == nil {
		var ret string
		return ret
	}
	return *o.TakenAtUserOverrideAt
}

// GetTakenAtUserOverrideAtOk returns a tuple with the TakenAtUserOverrideAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetTakenAtUserOverrideAtOk() (*string, bool) {
	if o == nil || o.TakenAtUserOverrideAt == nil {
		return nil, false
	}
	return o.TakenAtUserOverrideAt, true
}

// HasTakenAtUserOverrideAt returns a boolean if a field has been set.
func (o *Asset) HasTakenAtUserOverrideAt() bool {
	if o != nil && o.TakenAtUserOverrideAt != nil {
		return true
	}

	return false
}

// SetTakenAtUserOverrideAt gets a reference to the given string and assigns it to the TakenAtUserOverrideAt field.
func (o *Asset) SetTakenAtUserOverrideAt(v string) {
	o.TakenAtUserOverrideAt = &v
}

// GetDurationUnclipped returns the DurationUnclipped field value if set, zero value otherwise.
func (o *Asset) GetDurationUnclipped() string {
	if o == nil || o.DurationUnclipped == nil {
		var ret string
		return ret
	}
	return *o.DurationUnclipped
}

// GetDurationUnclippedOk returns a tuple with the DurationUnclipped field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetDurationUnclippedOk() (*string, bool) {
	if o == nil || o.DurationUnclipped == nil {
		return nil, false
	}
	return o.DurationUnclipped, true
}

// HasDurationUnclipped returns a boolean if a field has been set.
func (o *Asset) HasDurationUnclipped() bool {
	if o != nil && o.DurationUnclipped != nil {
		return true
	}

	return false
}

// SetDurationUnclipped gets a reference to the given string and assigns it to the DurationUnclipped field.
func (o *Asset) SetDurationUnclipped(v string) {
	o.DurationUnclipped = &v
}

// GetVideoClipStart returns the VideoClipStart field value if set, zero value otherwise.
func (o *Asset) GetVideoClipStart() string {
	if o == nil || o.VideoClipStart == nil {
		var ret string
		return ret
	}
	return *o.VideoClipStart
}

// GetVideoClipStartOk returns a tuple with the VideoClipStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetVideoClipStartOk() (*string, bool) {
	if o == nil || o.VideoClipStart == nil {
		return nil, false
	}
	return o.VideoClipStart, true
}

// HasVideoClipStart returns a boolean if a field has been set.
func (o *Asset) HasVideoClipStart() bool {
	if o != nil && o.VideoClipStart != nil {
		return true
	}

	return false
}

// SetVideoClipStart gets a reference to the given string and assigns it to the VideoClipStart field.
func (o *Asset) SetVideoClipStart(v string) {
	o.VideoClipStart = &v
}

// GetVideoClipExcludesAudio returns the VideoClipExcludesAudio field value if set, zero value otherwise.
func (o *Asset) GetVideoClipExcludesAudio() string {
	if o == nil || o.VideoClipExcludesAudio == nil {
		var ret string
		return ret
	}
	return *o.VideoClipExcludesAudio
}

// GetVideoClipExcludesAudioOk returns a tuple with the VideoClipExcludesAudio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetVideoClipExcludesAudioOk() (*string, bool) {
	if o == nil || o.VideoClipExcludesAudio == nil {
		return nil, false
	}
	return o.VideoClipExcludesAudio, true
}

// HasVideoClipExcludesAudio returns a boolean if a field has been set.
func (o *Asset) HasVideoClipExcludesAudio() bool {
	if o != nil && o.VideoClipExcludesAudio != nil {
		return true
	}

	return false
}

// SetVideoClipExcludesAudio gets a reference to the given string and assigns it to the VideoClipExcludesAudio field.
func (o *Asset) SetVideoClipExcludesAudio(v string) {
	o.VideoClipExcludesAudio = &v
}

// GetVideoClippedByUserAt returns the VideoClippedByUserAt field value if set, zero value otherwise.
func (o *Asset) GetVideoClippedByUserAt() string {
	if o == nil || o.VideoClippedByUserAt == nil {
		var ret string
		return ret
	}
	return *o.VideoClippedByUserAt
}

// GetVideoClippedByUserAtOk returns a tuple with the VideoClippedByUserAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetVideoClippedByUserAtOk() (*string, bool) {
	if o == nil || o.VideoClippedByUserAt == nil {
		return nil, false
	}
	return o.VideoClippedByUserAt, true
}

// HasVideoClippedByUserAt returns a boolean if a field has been set.
func (o *Asset) HasVideoClippedByUserAt() bool {
	if o != nil && o.VideoClippedByUserAt != nil {
		return true
	}

	return false
}

// SetVideoClippedByUserAt gets a reference to the given string and assigns it to the VideoClippedByUserAt field.
func (o *Asset) SetVideoClippedByUserAt(v string) {
	o.VideoClippedByUserAt = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *Asset) GetLocation() string {
	if o == nil || o.Location == nil {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetLocationOk() (*string, bool) {
	if o == nil || o.Location == nil {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *Asset) HasLocation() bool {
	if o != nil && o.Location != nil {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *Asset) SetLocation(v string) {
	o.Location = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *Asset) GetUser() User {
	if o == nil || o.User == nil {
		var ret User
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Asset) GetUserOk() (*User, bool) {
	if o == nil || o.User == nil {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *Asset) HasUser() bool {
	if o != nil && o.User != nil {
		return true
	}

	return false
}

// SetUser gets a reference to the given User and assigns it to the User field.
func (o *Asset) SetUser(v User) {
	o.User = &v
}

func (o Asset) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.UserId != nil {
		toSerialize["user_id"] = o.UserId
	}
	if o.ThumbnailUrl != nil {
		toSerialize["thumbnail_url"] = o.ThumbnailUrl
	}
	if o.PortraitUrl != nil {
		toSerialize["portrait_url"] = o.PortraitUrl
	}
	if o.LandscapeUrl != nil {
		toSerialize["landscape_url"] = o.LandscapeUrl
	}
	if o.Landscape1610Url != nil {
		toSerialize["landscape_16_10_url"] = o.Landscape1610Url
	}
	if o.Portrait45Url != nil {
		toSerialize["portrait_4_5_url"] = o.Portrait45Url
	}
	if o.VideoUrl != nil {
		toSerialize["video_url"] = o.VideoUrl
	}
	if o.LandscapeRect != nil {
		toSerialize["landscape_rect"] = o.LandscapeRect
	}
	if o.PortraitRect != nil {
		toSerialize["portrait_rect"] = o.PortraitRect
	}
	if o.UserLandscapeRect != nil {
		toSerialize["user_landscape_rect"] = o.UserLandscapeRect
	}
	if o.UserPortraitRect != nil {
		toSerialize["user_portrait_rect"] = o.UserPortraitRect
	}
	if o.AutoLandscape1610Rect != nil {
		toSerialize["auto_landscape_16_10_rect"] = o.AutoLandscape1610Rect
	}
	if o.UserLandscape1610Rect != nil {
		toSerialize["user_landscape_16_10_rect"] = o.UserLandscape1610Rect
	}
	if o.AutoPortrait45Rect != nil {
		toSerialize["auto_portrait_4_5_rect"] = o.AutoPortrait45Rect
	}
	if o.UserPortrait45Rect != nil {
		toSerialize["user_portrait_4_5_rect"] = o.UserPortrait45Rect
	}
	if o.ExifOrientation != nil {
		toSerialize["exif_orientation"] = o.ExifOrientation
	}
	if o.HandledAt != nil {
		toSerialize["handled_at"] = o.HandledAt
	}
	if o.UploadedAt != nil {
		toSerialize["uploaded_at"] = o.UploadedAt
	}
	if o.GoodResolution != nil {
		toSerialize["good_resolution"] = o.GoodResolution
	}
	if o.SourceId != nil {
		toSerialize["source_id"] = o.SourceId
	}
	if o.DuplicateOfId != nil {
		toSerialize["duplicate_of_id"] = o.DuplicateOfId
	}
	if o.RotationCw != nil {
		toSerialize["rotation_cw"] = o.RotationCw
	}
	if o.LocationName != nil {
		toSerialize["location_name"] = o.LocationName
	}
	if o.Md5Hash != nil {
		toSerialize["md5_hash"] = o.Md5Hash
	}
	if o.IsSubscription != nil {
		toSerialize["is_subscription"] = o.IsSubscription
	}
	if o.GlacieredAt != nil {
		toSerialize["glaciered_at"] = o.GlacieredAt
	}
	if o.Unglacierable != nil {
		toSerialize["unglacierable"] = o.Unglacierable
	}
	if o.Duration != nil {
		toSerialize["duration"] = o.Duration
	}
	if o.LivePhotoOff != nil {
		toSerialize["live_photo_off"] = o.LivePhotoOff
	}
	if o.LocalIdentifier != nil {
		toSerialize["local_identifier"] = o.LocalIdentifier
	}
	if o.CreatedAtOnClient != nil {
		toSerialize["created_at_on_client"] = o.CreatedAtOnClient
	}
	if o.Selected != nil {
		toSerialize["selected"] = o.Selected
	}
	if o.FileName != nil {
		toSerialize["file_name"] = o.FileName
	}
	if o.RawFileName != nil {
		toSerialize["raw_file_name"] = o.RawFileName
	}
	if o.VideoFileName != nil {
		toSerialize["video_file_name"] = o.VideoFileName
	}
	if o.Width != nil {
		toSerialize["width"] = o.Width
	}
	if o.Height != nil {
		toSerialize["height"] = o.Height
	}
	if o.TakenAt != nil {
		toSerialize["taken_at"] = o.TakenAt
	}
	if o.HorizontalAccuracy != nil {
		toSerialize["horizontal_accuracy"] = o.HorizontalAccuracy
	}
	if o.Favorite != nil {
		toSerialize["favorite"] = o.Favorite
	}
	if o.Orientation != nil {
		toSerialize["orientation"] = o.Orientation
	}
	if o.Hdr != nil {
		toSerialize["hdr"] = o.Hdr
	}
	if o.Panorama != nil {
		toSerialize["panorama"] = o.Panorama
	}
	if o.IsLive != nil {
		toSerialize["is_live"] = o.IsLive
	}
	if o.BurstId != nil {
		toSerialize["burst_id"] = o.BurstId
	}
	if o.BurstSelectionTypes != nil {
		toSerialize["burst_selection_types"] = o.BurstSelectionTypes
	}
	if o.RepresentsBurst != nil {
		toSerialize["represents_burst"] = o.RepresentsBurst
	}
	if o.DataUti != nil {
		toSerialize["data_uti"] = o.DataUti
	}
	if o.OriginalFileName != nil {
		toSerialize["original_file_name"] = o.OriginalFileName
	}
	if o.UploadPriority != nil {
		toSerialize["upload_priority"] = o.UploadPriority
	}
	if o.IosMediaSubtypes != nil {
		toSerialize["ios_media_subtypes"] = o.IosMediaSubtypes
	}
	if o.TakenAtUserOverrideAt != nil {
		toSerialize["taken_at_user_override_at"] = o.TakenAtUserOverrideAt
	}
	if o.DurationUnclipped != nil {
		toSerialize["duration_unclipped"] = o.DurationUnclipped
	}
	if o.VideoClipStart != nil {
		toSerialize["video_clip_start"] = o.VideoClipStart
	}
	if o.VideoClipExcludesAudio != nil {
		toSerialize["video_clip_excludes_audio"] = o.VideoClipExcludesAudio
	}
	if o.VideoClippedByUserAt != nil {
		toSerialize["video_clipped_by_user_at"] = o.VideoClippedByUserAt
	}
	if o.Location != nil {
		toSerialize["location"] = o.Location
	}
	if o.User != nil {
		toSerialize["user"] = o.User
	}
	return json.Marshal(toSerialize)
}

type NullableAsset struct {
	value *Asset
	isSet bool
}

func (v NullableAsset) Get() *Asset {
	return v.value
}

func (v *NullableAsset) Set(val *Asset) {
	v.value = val
	v.isSet = true
}

func (v NullableAsset) IsSet() bool {
	return v.isSet
}

func (v *NullableAsset) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAsset(val *Asset) *NullableAsset {
	return &NullableAsset{value: val, isSet: true}
}

func (v NullableAsset) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAsset) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


